'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Link from 'next/link'
import { useSession, signOut } from 'next-auth/react'
import { cn } from '@/lib/utils'
import IntakeWizard, { type IntakeData } from './IntakeWizard'
import {
  Plus,
  FileText,
  Home,
  LayoutTemplate,
  CreditCard,
  HelpCircle,
  Briefcase,
  Users,
  Lock,
  RotateCcw,
  Wrench,
  ClipboardList,
  Globe,
  Shield,
  ArrowRight,
  Check,
  Loader2,
  Eye,
  Download,
  ExternalLink,
  Search,
  // LogOut removed — account section uses text buttons now
  Menu,
  X,
  ChevronDown,
  Zap,
  Star,
} from 'lucide-react'

// ── Types ──────────────────────────────────────────────────────────────────────

type Tab = 'home' | 'new-contract' | 'my-contracts' | 'templates' | 'pricing' | 'help' | 'contract-view'
// Step 1 = choose type, 2 = intake wizard, 3 = loading, 4 = preview
type Step = 1 | 2 | 3 | 4

interface ContractType {
  id: string
  title: string
  description: string
  Icon: React.ComponentType<{ className?: string; style?: React.CSSProperties }>
}

type ContractStatus = 'draft' | 'sent' | 'completed' | 'expired'

interface SavedContract {
  id: string
  title: string
  typeId: string
  typeName: string
  party1: string
  party2: string
  party1Email: string
  party2Email: string
  status: ContractStatus
  createdAt: string
  sentAt?: string
  completedAt?: string
  content?: string
  intakeData?: Record<string, string | string[]>
}

// ── Data ───────────────────────────────────────────────────────────────────────

const CONTRACT_TYPES: ContractType[] = [
  { id: 'freelance', title: 'Freelance / Project Agreement', description: 'Scope, deliverables, payment terms and IP ownership.', Icon: Briefcase },
  { id: 'nda-mutual', title: 'NDA (Mutual)', description: 'Both parties protect each other\'s confidential information.', Icon: Users },
  { id: 'nda-one-way', title: 'NDA (One-Way)', description: 'One party discloses; the other agrees to protect it.', Icon: Lock },
  { id: 'retainer', title: 'Retainer Agreement', description: 'Ongoing services with a fixed monthly fee.', Icon: RotateCcw },
  { id: 'subcontractor', title: 'Subcontractor Agreement', description: 'Third-party contractor terms for client work.', Icon: Wrench },
  { id: 'client-service', title: 'Client Service Agreement', description: 'General terms for providing services to clients.', Icon: ClipboardList },
  { id: 'website-tcs', title: 'Website T&Cs', description: 'Terms, privacy policy and acceptable use for websites.', Icon: Globe },
  { id: 'employment-offer', title: 'Employment Offer Letter', description: 'Offer of employment with role, salary and conditions.', Icon: Shield },
]

const SIDEBAR_NAV: { id: Tab; label: string; Icon: React.ComponentType<{ className?: string; style?: React.CSSProperties }> }[] = [
  { id: 'home', label: 'Home', Icon: Home },
  { id: 'new-contract', label: 'New Contract', Icon: Plus },
  { id: 'my-contracts', label: 'My Contracts', Icon: FileText },
  { id: 'templates', label: 'Templates', Icon: LayoutTemplate },
  { id: 'pricing', label: 'Pricing', Icon: CreditCard },
  { id: 'help', label: 'Help', Icon: HelpCircle },
]

const LOADING_MESSAGES = [
  'Drafting your contract\u2026',
  'Applying UK legal clauses\u2026',
  'Checking IR35 compliance\u2026',
  'Finalising your document\u2026',
]

const LS_KEY = 'clausekit_contracts'

function loadSaved(): SavedContract[] {
  if (typeof window === 'undefined') return []
  try { return JSON.parse(localStorage.getItem(LS_KEY) ?? '[]') } catch { return [] }
}
function persistSaved(c: SavedContract[]) {
  if (typeof window !== 'undefined') localStorage.setItem(LS_KEY, JSON.stringify(c))
}

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

// ── FAQ data ───────────────────────────────────────────────────────────────────

const FAQS = [
  { q: 'Are ClauseKit contracts legally binding?', a: 'Yes. Contracts generated by ClauseKit are legally binding when properly executed by both parties. They are drafted to comply with UK law. For high-value or complex matters, we recommend review by a qualified solicitor.' },
  { q: 'What happens after I generate a contract?', a: 'You\u2019ll see a preview of your contract immediately. To download the full PDF and Word versions, you pay a one-time \u00A37 fee via Stripe. Your contract is available for instant download.' },
  { q: 'Can I edit the contract after downloading?', a: 'Yes \u2014 the Word (.docx) version is fully editable. Make any adjustments before sending to the other party.' },
  { q: 'Is my data secure?', a: 'We don\u2019t store your contract content after generation. Payments are processed securely by Stripe. We never share your data with third parties.' },
  { q: 'What if I need a contract type that isn\u2019t listed?', a: 'Use the \u201cClient Service Agreement\u201d or \u201cFreelance / Project Agreement\u201d types \u2014 they cover most situations. Describe your exact needs in the description field and ClauseKit will tailor accordingly.' },
]

// ── Sub-components ─────────────────────────────────────────────────────────────

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="border-b last:border-b-0" style={{ borderColor: '#E5E5E2' }}>
      <button className="w-full flex items-center justify-between py-4 text-left" onClick={() => setOpen(!open)}>
        <span className="text-sm font-semibold pr-4" style={{ color: '#1B4332' }}>{q}</span>
        <motion.div animate={{ rotate: open ? 180 : 0 }} transition={{ duration: 0.2 }}>
          <ChevronDown className="w-4 h-4 flex-shrink-0" style={{ color: '#6B7280' }} />
        </motion.div>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22 }}
            className="overflow-hidden"
          >
            <p className="pb-4 text-sm leading-relaxed" style={{ color: '#6B7280' }}>{a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

// ── Checkout helper ────────────────────────────────────────────────────────────

async function initiateCheckout(contractId: string): Promise<void> {
  const res = await fetch('/api/checkout', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ contractId }),
  })
  const data = await res.json()
  if (data.url) {
    window.location.href = data.url
  } else {
    throw new Error(data.error ?? 'Checkout failed')
  }
}

// ── Status badge ──────────────────────────────────────────────────────────────

function StatusBadge({ status }: { status: ContractStatus }) {
  const map: Record<ContractStatus, { bg: string; color: string; label: string }> = {
    draft:     { bg: '#FEF3C7', color: '#92400E', label: 'Draft' },
    sent:      { bg: '#DBEAFE', color: '#1E40AF', label: 'Sent' },
    completed: { bg: '#D8F3DC', color: '#1B4332', label: 'Completed' },
    expired:   { bg: '#FEE2E2', color: '#991B1B', label: 'Expired' },
  }
  const s = map[status] ?? map.draft
  return <span className="text-xs font-bold px-2 py-0.5 uppercase tracking-wide" style={{ backgroundColor: s.bg, color: s.color }}>{s.label}</span>
}

// ── My Contracts Tab ──────────────────────────────────────────────────────────

type ContractsTabFilter = 'all' | ContractStatus

function MyContractsTab({ savedContracts, searchQuery, onNew, onCheckout, onView }: {
  savedContracts: SavedContract[]; searchQuery: string; onNew: () => void; onCheckout: (id: string) => void; onView: (id: string) => void
}) {
  const [af, setAf] = useState<ContractsTabFilter>('all')
  const counts: Record<ContractsTabFilter, number> = {
    all: savedContracts.length,
    draft: savedContracts.filter((c) => c.status === 'draft').length,
    sent: savedContracts.filter((c) => c.status === 'sent').length,
    completed: savedContracts.filter((c) => c.status === 'completed').length,
    expired: savedContracts.filter((c) => c.status === 'expired').length,
  }
  const list = savedContracts.filter((c) => {
    const mf = af === 'all' || c.status === af
    const ms = !searchQuery || c.title.toLowerCase().includes(searchQuery.toLowerCase()) || c.typeName.toLowerCase().includes(searchQuery.toLowerCase())
    return mf && ms
  })
  const tabs: { key: ContractsTabFilter; label: string }[] = [
    { key: 'all', label: 'All' }, { key: 'draft', label: 'Draft' }, { key: 'sent', label: 'Sent' }, { key: 'completed', label: 'Completed' }, { key: 'expired', label: 'Expired' },
  ]
  return (
    <motion.div key="my-contracts" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
      <div className="flex items-center justify-between mb-5">
        <h1 className="font-display text-2xl font-bold" style={{ color: '#1B4332' }}>My Contracts</h1>
        <button onClick={onNew} className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white hover:opacity-90" style={{ backgroundColor: '#2D6A4F' }}>
          <Plus className="w-4 h-4" /> New Contract
        </button>
      </div>
      <div className="flex border-b mb-5" style={{ borderColor: '#E5E5E2' }}>
        {tabs.map((t) => (
          <button key={t.key} onClick={() => setAf(t.key)} className="flex items-center gap-1.5 px-4 py-2.5 text-xs font-semibold border-b-2 -mb-px" style={af === t.key ? { borderBottomColor: '#2D6A4F', color: '#1B4332' } : { borderBottomColor: 'transparent', color: '#9CA3AF' }}>
            {t.label}
            {counts[t.key] > 0 && <span className="px-1.5 py-0.5 text-xs font-bold" style={af === t.key ? { backgroundColor: '#D8F3DC', color: '#1B4332' } : { backgroundColor: '#F3F4F6', color: '#9CA3AF' }}>{counts[t.key]}</span>}
          </button>
        ))}
      </div>
      {list.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center border" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
          <div className="w-12 h-12 flex items-center justify-center mb-4" style={{ backgroundColor: '#D8F3DC' }}><FileText className="w-6 h-6" style={{ color: '#2D6A4F' }} /></div>
          <h2 className="font-display text-base font-bold mb-2" style={{ color: '#1B4332' }}>{searchQuery ? 'No contracts match your search' : af === 'all' ? 'No contracts yet' : `No ${af} contracts`}</h2>
          {!searchQuery && af === 'all' && <button onClick={onNew} className="mt-3 flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white" style={{ backgroundColor: '#2D6A4F' }}><Plus className="w-4 h-4" /> Create contract</button>}
        </div>
      ) : (
        <div className="border" style={{ borderColor: '#E5E5E2' }}>
          <div className="flex items-center gap-4 px-4 py-2.5 border-b text-xs font-bold uppercase tracking-widest" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8', color: '#9CA3AF' }}>
            <div className="flex-1">Contract</div><div className="w-24 hidden sm:block text-center">Status</div><div className="w-32 hidden md:block text-right">Date</div><div className="w-28 text-right">Action</div>
          </div>
          {list.map((c, i) => (
            <div key={c.id} className={cn('flex items-center gap-4 px-4 py-3.5 hover:bg-[#FAFAF8] transition-colors', i !== 0 && 'border-t')} style={{ borderColor: '#E5E5E2' }}>
              <button onClick={() => onView(c.id)} className="flex items-center gap-4 flex-1 min-w-0 text-left">
              <FileText className="w-4 h-4 flex-shrink-0" style={{ color: '#9CA3AF' }} />
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium truncate mb-0.5" style={{ color: '#1B4332' }}>{c.title}</p>
                <p className="text-xs truncate" style={{ color: '#9CA3AF' }}>{c.typeName}{c.party2 ? ` · ${c.party2}` : ''}</p>
              </div>
              </button>
              <div className="w-24 hidden sm:flex justify-center flex-shrink-0"><StatusBadge status={c.status} /></div>
              <div className="w-32 hidden md:block text-right text-xs flex-shrink-0" style={{ color: '#9CA3AF' }}>{c.completedAt ? fmtDate(c.completedAt) : c.sentAt ? fmtDate(c.sentAt) : fmtDate(c.createdAt)}</div>
              <div className="w-28 flex justify-end flex-shrink-0">
                {c.status === 'draft' && <button onClick={() => onCheckout(c.id)} className="text-xs font-semibold flex items-center gap-1 hover:opacity-70" style={{ color: '#2D6A4F' }}><Download className="w-3 h-3" /> Unlock</button>}
                {c.status === 'sent' && <span className="text-xs font-semibold flex items-center gap-1" style={{ color: '#1E40AF' }}><Eye className="w-3 h-3" /> Awaiting</span>}
                {c.status === 'completed' && <a href={`/download/${c.id}`} className="text-xs font-semibold flex items-center gap-1 hover:opacity-70" style={{ color: '#2D6A4F' }}><Download className="w-3 h-3" /> Download</a>}
                {c.status === 'expired' && <button onClick={onNew} className="text-xs font-semibold flex items-center gap-1 hover:opacity-70" style={{ color: '#9CA3AF' }}><Plus className="w-3 h-3" /> Redo</button>}
              </div>
            </div>
          ))}
        </div>
      )}
    </motion.div>
  )
}

// ── Contract Viewer ────────────────────────────────────────────────────────────

function ContractViewer({ contract, onBack, onCheckout, onUpdate }: {
  contract: SavedContract
  onBack: () => void
  onCheckout: (id: string) => void
  onUpdate: (updated: SavedContract) => void
}) {
  const [sideTab, setSideTab] = useState<'parties' | 'details' | 'terms'>('parties')
  const [editableContent, setEditableContent] = useState(contract.content ?? '')
  const [editableTitle, setEditableTitle] = useState(contract.title)
  const [checkoutLoading, setCheckoutLoading] = useState(false)

  // Debounced save
  useEffect(() => {
    const t = setTimeout(() => {
      onUpdate({ ...contract, content: editableContent, title: editableTitle })
    }, 500)
    return () => clearTimeout(t)
  }, [editableContent, editableTitle]) // eslint-disable-line react-hooks/exhaustive-deps

  // Parse contract text into blocks
  const blocks = editableContent.split(/\n\n+/).filter(Boolean)

  const intake = contract.intakeData ?? {}

  const KEY_TERM_LABELS: Record<string, string> = {
    feeAmount: 'Fee',
    feeStructure: 'Fee structure',
    paymentTerms: 'Payment terms',
    paymentSchedule: 'Payment schedule',
    ipTransfer: 'IP transfer',
    noticePeriod: 'Notice period',
    ndaDuration: 'NDA duration',
    ndaScope: 'NDA scope',
    retainerFee: 'Monthly retainer',
    minimumTerm: 'Minimum term',
    jobTitle: 'Job title',
    annualSalary: 'Annual salary',
    hoursPerWeek: 'Hours per week',
    holidayDays: 'Holiday days',
    probationPeriod: 'Probation period',
    revisionsIncluded: 'Revisions included',
    deliverables: 'Deliverables',
    retainerServices: 'Services',
    confidentialityDuration: 'Confidentiality',
  }

  const keyTerms = Object.entries(KEY_TERM_LABELS)
    .filter(([k]) => intake[k] && String(intake[k]).trim())
    .map(([k, label]) => ({ label, value: String(intake[k]) }))

  // Classify line types
  const classifyBlock = (text: string): 'section-heading' | 'party-block' | 'signature' | 'footer' | 'body' => {
    const t = text.trim()
    if (/^\d{2}\.\s+[A-Z]/.test(t)) return 'section-heading'
    if (t.startsWith('PARTY 1') || t.startsWith('PARTY 2')) return 'party-block'
    if (t.startsWith('ACCEPTANCE') || t.includes('Signature:') || t.startsWith('PARTY 1 —') || t.startsWith('PARTY 2 —')) return 'signature'
    if (t.startsWith('---') || t.startsWith('This document was generated')) return 'footer'
    if (t === t.toUpperCase() && t.length > 5 && t.length < 60 && !t.startsWith('-')) return 'section-heading'
    return 'body'
  }

  return (
    <div className="flex h-full overflow-hidden">
      {/* ── Left: Editable Document ── */}
      <div className="flex-1 overflow-y-auto" style={{ backgroundColor: '#FFFFFF' }}>
        <div className="max-w-3xl mx-auto px-8 py-10">
          {/* Back */}
          <button onClick={onBack} className="flex items-center gap-1.5 text-xs mb-6 hover:opacity-70 transition-opacity" style={{ color: '#6B7280' }}>
            &larr; Back to dashboard
          </button>

          {/* Header block */}
          <div className="border-b pb-6 mb-8" style={{ borderColor: '#E5E5E2' }}>
            <div
              contentEditable
              suppressContentEditableWarning
              onBlur={(e) => setEditableTitle(e.currentTarget.textContent ?? '')}
              className="font-display text-3xl font-bold mb-2 outline-none focus:bg-[#FAFAF8] px-1 -mx-1"
              style={{ color: '#1B4332', minHeight: '2rem' }}
            >
              {contract.title}
            </div>
            <p className="text-xs" style={{ color: '#9CA3AF' }}>
              {contract.typeName} &middot; Generated {new Date(contract.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} &middot; Click any text to edit
            </p>
          </div>

          {/* Document body — parsed sections */}
          <div>
            {blocks.map((block, i) => {
              const type = classifyBlock(block)

              if (type === 'section-heading') {
                return (
                  <div key={i} className="mt-8 mb-3">
                    <div className="border-b pb-2 mb-3" style={{ borderColor: '#E5E5E2' }}>
                      <div
                        contentEditable
                        suppressContentEditableWarning
                        onBlur={(e) => {
                          const nb = [...blocks]; nb[i] = e.currentTarget.textContent ?? ''; setEditableContent(nb.join('\n\n'))
                        }}
                        className="text-sm font-bold uppercase tracking-wide outline-none focus:bg-[#FAFAF8] px-1 -mx-1"
                        style={{ color: '#1B4332' }}
                      >
                        {block}
                      </div>
                    </div>
                  </div>
                )
              }

              if (type === 'party-block') {
                return (
                  <div key={i} className="mb-4 p-4 border-l-4" style={{ borderLeftColor: '#2D6A4F', backgroundColor: '#FAFAF8' }}>
                    <div
                      contentEditable
                      suppressContentEditableWarning
                      onBlur={(e) => {
                        const nb = [...blocks]; nb[i] = e.currentTarget.textContent ?? ''; setEditableContent(nb.join('\n\n'))
                      }}
                      className="text-sm leading-relaxed outline-none"
                      style={{ color: '#374151' }}
                    >
                      {block}
                    </div>
                  </div>
                )
              }

              if (type === 'signature') {
                return (
                  <div key={i} className="mt-8 pt-6 border-t" style={{ borderColor: '#1B4332' }}>
                    <div
                      contentEditable
                      suppressContentEditableWarning
                      onBlur={(e) => {
                        const nb = [...blocks]; nb[i] = e.currentTarget.textContent ?? ''; setEditableContent(nb.join('\n\n'))
                      }}
                      className="text-sm font-semibold leading-loose outline-none focus:bg-[#FAFAF8] px-1 -mx-1"
                      style={{ color: '#1B4332' }}
                    >
                      {block}
                    </div>
                  </div>
                )
              }

              if (type === 'footer') {
                return (
                  <div key={i} className="mt-8 pt-4 border-t text-center" style={{ borderColor: '#E5E5E2' }}>
                    <p className="text-xs" style={{ color: '#9CA3AF' }}>{block}</p>
                  </div>
                )
              }

              // Body text
              return (
                <div
                  key={i}
                  contentEditable
                  suppressContentEditableWarning
                  onBlur={(e) => {
                    const nb = [...blocks]; nb[i] = e.currentTarget.textContent ?? ''; setEditableContent(nb.join('\n\n'))
                  }}
                  className="text-sm leading-relaxed mb-3 outline-none focus:bg-[#FAFAF8] px-1 -mx-1"
                  style={{ color: '#374151', minHeight: '1.2rem' }}
                >
                  {block}
                </div>
              )
            })}
          </div>

          {blocks.length === 0 && (
            <p className="text-sm italic" style={{ color: '#9CA3AF' }}>No contract content yet.</p>
          )}
        </div>
      </div>

      {/* ── Right: Info Sidebar ── */}
      <div className="w-80 flex-shrink-0 flex flex-col border-l overflow-hidden" style={{ backgroundColor: '#FAFAF8', borderColor: '#E5E5E2' }}>
        {/* Tabs */}
        <div className="flex border-b flex-shrink-0" style={{ borderColor: '#E5E5E2' }}>
          {(['parties', 'details', 'terms'] as const).map((t) => (
            <button
              key={t}
              onClick={() => setSideTab(t)}
              className="flex-1 py-2.5 text-xs font-semibold capitalize transition-colors"
              style={sideTab === t
                ? { backgroundColor: '#D8F3DC', color: '#1B4332', borderBottom: '2px solid #2D6A4F' }
                : { backgroundColor: 'transparent', color: '#9CA3AF', borderBottom: '2px solid transparent' }
              }
            >
              {t === 'parties' ? 'Parties' : t === 'details' ? 'Details' : 'Key Terms'}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {sideTab === 'parties' && (
            <>
              <div>
                <p className="text-xs font-bold uppercase tracking-widest mb-2" style={{ color: '#2D6A4F' }}>Party 1 — You</p>
                {[
                  { label: 'Name', value: contract.party1 },
                  { label: 'Email', value: contract.party1Email },
                  { label: 'Address', value: String(intake.yourAddress ?? '') },
                  { label: 'Company no.', value: String(intake.yourCompanyNumber ?? '') },
                  { label: 'VAT no.', value: String(intake.yourVatNumber ?? '') },
                ].filter(r => r.value).map(r => (
                  <div key={r.label} className="mb-2">
                    <p className="text-xs font-medium" style={{ color: '#9CA3AF' }}>{r.label}</p>
                    <p className="text-sm" style={{ color: '#1B4332' }}>{r.value}</p>
                  </div>
                ))}
              </div>
              <div className="border-t pt-4" style={{ borderColor: '#E5E5E2' }}>
                <p className="text-xs font-bold uppercase tracking-widest mb-2" style={{ color: '#2D6A4F' }}>Party 2 — Client</p>
                {[
                  { label: 'Name', value: contract.party2 },
                  { label: 'Email', value: contract.party2Email },
                  { label: 'Address', value: String(intake.theirAddress ?? '') },
                  { label: 'Contact', value: String(intake.theirContactName ?? '') },
                ].filter(r => r.value).map(r => (
                  <div key={r.label} className="mb-2">
                    <p className="text-xs font-medium" style={{ color: '#9CA3AF' }}>{r.label}</p>
                    <p className="text-sm" style={{ color: '#1B4332' }}>{r.value}</p>
                  </div>
                ))}
              </div>
            </>
          )}

          {sideTab === 'details' && (
            <>
              {[
                { label: 'Contract type', value: contract.typeName },
                { label: 'Status', value: contract.status.charAt(0).toUpperCase() + contract.status.slice(1) },
                { label: 'Generated', value: new Date(contract.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) },
                { label: 'Governing law', value: String(intake.governingLaw ?? 'England & Wales') },
                { label: 'Start date', value: String(intake.contractStartDate ?? '') },
                { label: 'Contract ID', value: contract.id },
              ].filter(r => r.value).map(r => (
                <div key={r.label} className="mb-3">
                  <p className="text-xs font-medium mb-0.5" style={{ color: '#9CA3AF' }}>{r.label}</p>
                  <p className={`text-sm break-all ${r.label === 'Contract ID' ? 'font-mono text-xs' : ''}`} style={{ color: '#1B4332' }}>{r.value}</p>
                </div>
              ))}
            </>
          )}

          {sideTab === 'terms' && (
            keyTerms.length > 0 ? keyTerms.map(t => (
              <div key={t.label} className="mb-3">
                <p className="text-xs font-medium mb-0.5" style={{ color: '#9CA3AF' }}>{t.label}</p>
                <p className="text-sm" style={{ color: '#1B4332' }}>{t.value}</p>
              </div>
            )) : (
              <p className="text-xs italic" style={{ color: '#9CA3AF' }}>No key terms available for this contract type.</p>
            )
          )}
        </div>

        {/* Download / paywall */}
        <div className="flex-shrink-0 border-t p-4 space-y-2" style={{ borderColor: '#E5E5E2', backgroundColor: '#FFFFFF' }}>
          {contract.status === 'completed' ? (
            <a href={`/download/${contract.id}`} className="flex items-center justify-center gap-2 w-full py-2.5 text-sm font-semibold text-white" style={{ backgroundColor: '#2D6A4F' }}>
              <Download className="w-4 h-4" /> Download PDF + Word
            </a>
          ) : (
            <>
              <button
                onClick={async () => {
                  setCheckoutLoading(true)
                  await onCheckout(contract.id)
                  setCheckoutLoading(false)
                }}
                disabled={checkoutLoading}
                className="flex items-center justify-center gap-2 w-full py-2.5 text-sm font-semibold text-white transition-opacity hover:opacity-90 disabled:opacity-60"
                style={{ backgroundColor: '#2D6A4F' }}
              >
                {checkoutLoading ? <><Loader2 className="w-4 h-4 animate-spin" /> Redirecting…</> : <><Download className="w-4 h-4" /> £7 — Download PDF + Word</>}
              </button>
              <p className="text-xs text-center" style={{ color: '#9CA3AF' }}>Free to edit · Pay £7 to download · Secure via Stripe</p>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Page ───────────────────────────────────────────────────────────────────────

export default function AppDashboard() {
  const { data: session } = useSession()
  const [activeTab, setActiveTab] = useState<Tab>('home')
  const [step, setStep] = useState<Step>(1)
  const [selectedType, setSelectedType] = useState<ContractType | null>(null)
  const [, setIntakeData] = useState<IntakeData | null>(null)
  const [loadingMsg, setLoadingMsg] = useState(0)
  const [contractId, setContractId] = useState<string | null>(null)
  const [contractContent, setContractContent] = useState<string | null>(null)
  const [contractTitle, setContractTitle] = useState<string | null>(null)
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [error, setError] = useState<string | null>(null)
  const [checkoutLoading, setCheckoutLoading] = useState(false)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [savedContracts, setSavedContracts] = useState<SavedContract[]>([])
  const [searchQuery, setSearchQuery] = useState('')
  const [viewingContractId, setViewingContractId] = useState<string | null>(null)

  useEffect(() => { setSavedContracts(loadSaved()) }, [])

  // Loading message cycle
  useEffect(() => {
    if (step !== 3) return
    const t = setInterval(() => setLoadingMsg((v) => Math.min(v + 1, LOADING_MESSAGES.length - 1)), 1800)
    return () => clearInterval(t)
  }, [step])

  const navigate = (tab: Tab) => {
    setActiveTab(tab)
    setSidebarOpen(false)
    if (tab === 'new-contract') handleReset()
  }

  const handleSelectType = (type: ContractType) => {
    setSelectedType(type)
    setStep(2)
    setActiveTab('new-contract')
  }

  const handleGenerate = async (intake: IntakeData) => {
    if (!selectedType) return
    setIntakeData(intake)
    setError(null)
    setLoadingMsg(0)
    setStep(3)
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contractType: selectedType.id,
          fields: intake,
        }),
      })
      if (!res.ok) {
        const body = await res.json().catch(() => ({}))
        throw new Error(body.error ?? 'Generation failed')
      }
      const data = await res.json()
      // API returns contractId (not id)
      const id = data.contractId ?? data.id
      setContractId(id)
      setContractContent(data.content)
      setContractTitle(data.title)
      setStep(4)

      // Persist to localStorage
      const entry: SavedContract = {
        id,
        title: data.title ?? selectedType.title,
        typeId: selectedType.id,
        typeName: selectedType.title,
        party1: (intake.yourName as string) ?? '',
        party2: (intake.theirName as string) ?? '',
        party1Email: (intake.yourEmail as string) ?? '',
        party2Email: (intake.theirEmail as string) ?? '',
        status: 'draft',
        createdAt: new Date().toISOString(),
        content: data.content,
        intakeData: intake as unknown as Record<string, string | string[]>,
      }
      const updated = [entry, ...loadSaved()]
      persistSaved(updated)
      setSavedContracts(updated)

      // Navigate to contract viewer
      setViewingContractId(id)
      setActiveTab('contract-view')
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Something went wrong')
      setStep(2)
    }
  }

  const handleCheckout = async () => {
    if (!contractId) return
    setCheckoutLoading(true)
    try {
      await initiateCheckout(contractId)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Checkout failed')
      setCheckoutLoading(false)
    }
  }

  const handleReset = () => {
    setStep(1)
    setSelectedType(null)
    setIntakeData(null)
    setContractId(null)
    setContractContent(null)
    setContractTitle(null)
    setError(null)
    setLoadingMsg(0)
    setCheckoutLoading(false)
  }

  const stats = {
    total: savedContracts.length,
    generated: savedContracts.filter((c) => c.status === 'draft').length,
    paid: savedContracts.filter((c) => c.status === 'completed').length,
  }

  // filtered is used inside MyContractsTab — kept for search propagation

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="flex flex-col h-screen overflow-hidden" style={{ backgroundColor: '#FAFAF8' }}>

      {/* ── UK TRUST BANNER (full width) ── */}
      <div className="flex items-center justify-center gap-3 px-4 py-2 text-xs font-medium flex-shrink-0 w-full" style={{ backgroundColor: '#1B4332', color: '#D8F3DC' }}>
        <span className="flex items-center gap-1.5">
          <svg className="w-3.5 h-3.5 flex-shrink-0" viewBox="0 0 24 24" fill="currentColor"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z"/></svg>
          UK law only
        </span>
        <span style={{ color: '#52B788' }}>·</span>
        <span>IR35-aware</span>
        <span style={{ color: '#52B788' }}>·</span>
        <span>Solicitor-reviewed</span>
        <span style={{ color: '#52B788' }}>·</span>
        <span>Not a template — bespoke every time</span>
        <span style={{ color: '#52B788' }}>·</span>
        <span className="font-bold" style={{ color: '#52B788' }}>£7 to download</span>
      </div>

      <div className="flex flex-1 overflow-hidden">

      {/* ── SIDEBAR ── */}
      <aside
        className={cn(
          'flex-shrink-0 flex flex-col h-full z-40 transition-transform duration-200',
          'w-[220px] border-r',
          'max-md:fixed max-md:top-0 max-md:left-0 max-md:shadow-xl',
          sidebarOpen ? 'max-md:translate-x-0' : 'max-md:-translate-x-full',
        )}
        style={{ backgroundColor: '#FFFFFF', borderColor: '#E5E5E2' }}
      >
        {/* Logo */}
        <div className="px-5 h-12 flex items-center border-b flex-shrink-0" style={{ borderColor: '#E5E5E2' }}>
          <Link href="/" className="flex items-center gap-2">
            <div className="w-6 h-6 flex items-center justify-center" style={{ backgroundColor: '#2D6A4F' }}>
              <FileText className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-bold text-sm tracking-tight" style={{ color: '#1B4332' }}>ClauseKit</span>
          </Link>
        </div>

        {/* Nav */}
        <nav className="flex-1 py-2 overflow-y-auto">
          {SIDEBAR_NAV.map((item) => {
            const Icon = item.Icon
            const isActive = activeTab === item.id
            return (
              <button
                key={item.id}
                onClick={() => navigate(item.id)}
                className={cn(
                  'w-full flex items-center gap-3 px-4 py-2.5 text-sm font-medium transition-all text-left border-l-2',
                  isActive ? '' : 'hover:bg-[#FAFAF8] border-l-transparent',
                )}
                style={isActive ? { backgroundColor: '#EDFAF2', color: '#1B4332', borderLeftColor: '#2D6A4F' } : { color: '#6B7280' }}
              >
                <Icon className="w-4 h-4 flex-shrink-0" style={{ color: isActive ? '#2D6A4F' : '#9CA3AF' }} />
                {item.label}
              </button>
            )
          })}
        </nav>

        {/* Upgrade nudge */}
        <div className="mx-3 mb-3 p-3 border" style={{ backgroundColor: '#EDFAF2', borderColor: '#52B78840' }}>
          <p className="text-xs font-semibold mb-0.5" style={{ color: '#1B4332' }}>Unlimited access</p>
          <p className="text-xs mb-2" style={{ color: '#52B788' }}>&pound;19/mo &mdash; all types, unlimited</p>
          <button
            onClick={() => navigate('pricing')}
            className="w-full py-1.5 text-xs font-semibold text-white transition-opacity hover:opacity-90"
            style={{ backgroundColor: '#2D6A4F' }}
          >
            Upgrade
          </button>
        </div>

        {/* Account section */}
        <div className="border-t flex-shrink-0" style={{ borderColor: '#E5E5E2' }}>
          {session ? (
            <div className="px-4 py-3">
              <div className="flex items-center gap-2.5 mb-2">
                <div className="w-7 h-7 flex items-center justify-center text-xs font-bold text-white flex-shrink-0" style={{ backgroundColor: '#2D6A4F' }}>
                  {(session.user?.name ?? session.user?.email ?? 'U').slice(0, 2).toUpperCase()}
                </div>
                <div className="min-w-0 flex-1">
                  <p className="text-xs font-semibold truncate" style={{ color: '#1B4332' }}>{session.user?.name ?? 'User'}</p>
                  <p className="text-xs truncate" style={{ color: '#9CA3AF' }}>{session.user?.email}</p>
                </div>
              </div>
              <div className="flex gap-2">
                <button onClick={() => navigate('settings' as Tab)} className="flex-1 text-xs font-medium py-1.5 border hover:bg-[#FAFAF8] transition-colors" style={{ borderColor: '#E5E5E2', color: '#6B7280' }}>
                  Settings
                </button>
                <button onClick={() => signOut({ callbackUrl: '/' })} className="flex-1 text-xs font-medium py-1.5 border hover:bg-[#FAFAF8] transition-colors" style={{ borderColor: '#E5E5E2', color: '#6B7280' }}>
                  Sign out
                </button>
              </div>
            </div>
          ) : (
            <div className="px-4 py-3">
              <Link href="/auth/signin" className="w-full flex items-center justify-center py-2 text-xs font-semibold text-white" style={{ backgroundColor: '#2D6A4F' }}>
                Sign in
              </Link>
            </div>
          )}
        </div>
      </aside>

      {/* Mobile overlay */}
      {sidebarOpen && <div className="md:hidden fixed inset-0 z-30 bg-black/20" onClick={() => setSidebarOpen(false)} />}

      {/* ── MAIN ── */}
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">

        {/* Top bar */}
        <div className="flex items-center gap-3 px-4 h-12 border-b flex-shrink-0 bg-white" style={{ borderColor: '#E5E5E2' }}>
          <button className="md:hidden p-1 text-gray-500" onClick={() => setSidebarOpen(!sidebarOpen)} aria-label="Menu">
            {sidebarOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
          </button>

          {/* Search */}
          <div className="flex-1 flex items-center gap-2 border px-3 py-1.5 max-w-md" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
            <Search className="w-3.5 h-3.5 flex-shrink-0" style={{ color: '#9CA3AF' }} />
            <input
              type="text"
              placeholder="Search contracts..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="text-sm bg-transparent outline-none w-full placeholder-gray-400"
              style={{ color: '#1A1A1A' }}
            />
          </div>

          <div className="ml-auto flex items-center gap-2">
            {session ? (
              <div className="flex items-center gap-2">
                <div className="w-7 h-7 flex items-center justify-center text-xs font-bold text-white" style={{ backgroundColor: '#2D6A4F' }} title={session.user?.email ?? ''}>
                  {(session.user?.name ?? session.user?.email ?? 'U').slice(0, 2).toUpperCase()}
                </div>
                <button onClick={() => signOut({ callbackUrl: '/' })} className="text-xs hover:opacity-70 hidden sm:block" style={{ color: '#9CA3AF' }}>
                  Sign out
                </button>
              </div>
            ) : (
              <Link href="/auth/signin" className="text-xs font-semibold px-3 py-1.5 border hover:bg-[#D8F3DC]" style={{ borderColor: '#2D6A4F', color: '#2D6A4F' }}>
                Sign in
              </Link>
            )}
          </div>
        </div>

        {/* Content */}
        <main className="flex-1 overflow-y-auto bg-white">
          <AnimatePresence mode="wait">

            {/* ── HOME ── */}
            {activeTab === 'home' && (
              <motion.div key="home" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <h1 className="font-display text-2xl font-bold" style={{ color: '#1B4332' }}>Welcome back</h1>
                    <p className="text-sm mt-0.5" style={{ color: '#6B7280' }}>Generate a UK-compliant contract in under 2 minutes.</p>
                  </div>
                  <button
                    onClick={() => navigate('new-contract')}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white transition-opacity hover:opacity-90"
                    style={{ backgroundColor: '#2D6A4F' }}
                  >
                    <Plus className="w-4 h-4" /> New Contract
                  </button>
                </div>

                {/* Stats */}
                <div className="grid grid-cols-3 border mb-8" style={{ borderColor: '#E5E5E2' }}>
                  {[
                    { label: 'Contracts generated', value: stats.total },
                    { label: 'Awaiting download', value: stats.generated },
                    { label: 'Downloaded', value: stats.paid },
                  ].map((s, i) => (
                    <div key={i} className={cn('p-4', i !== 2 && 'border-r')} style={{ borderColor: '#E5E5E2' }}>
                      <p className="text-xs font-medium mb-1" style={{ color: '#9CA3AF' }}>{s.label}</p>
                      <p className="font-display text-2xl font-bold" style={{ color: '#1B4332' }}>{s.value}</p>
                    </div>
                  ))}
                </div>

                {/* Quick-start contract types */}
                <div className="mb-8">
                  <h2 className="text-xs font-bold uppercase tracking-widest mb-3" style={{ color: '#9CA3AF' }}>Quick start</h2>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                    {CONTRACT_TYPES.slice(0, 4).map((c) => {
                      const Icon = c.Icon
                      return (
                        <button
                          key={c.id}
                          onClick={() => handleSelectType(c)}
                          className="flex items-center gap-3 p-3 border text-left hover:border-[#2D6A4F] hover:bg-[#FAFAF8] transition-all"
                          style={{ borderColor: '#E5E5E2', backgroundColor: '#FFFFFF' }}
                        >
                          <div className="w-8 h-8 flex items-center justify-center flex-shrink-0" style={{ backgroundColor: '#D8F3DC' }}>
                            <Icon className="w-4 h-4" style={{ color: '#2D6A4F' }} />
                          </div>
                          <span className="text-xs font-semibold leading-snug" style={{ color: '#1B4332' }}>{c.title}</span>
                        </button>
                      )
                    })}
                  </div>
                </div>

                {/* Recent contracts */}
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <h2 className="text-xs font-bold uppercase tracking-widest" style={{ color: '#9CA3AF' }}>Recent contracts</h2>
                    {savedContracts.length > 0 && (
                      <button onClick={() => navigate('my-contracts')} className="text-xs font-medium hover:opacity-70" style={{ color: '#2D6A4F' }}>
                        View all
                      </button>
                    )}
                  </div>

                  {savedContracts.length === 0 ? (
                    <div className="flex flex-col items-center justify-center py-16 text-center border" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                      <div className="w-12 h-12 flex items-center justify-center mb-4" style={{ backgroundColor: '#D8F3DC' }}>
                        <FileText className="w-6 h-6" style={{ color: '#2D6A4F' }} />
                      </div>
                      <h3 className="font-display text-base font-bold mb-2" style={{ color: '#1B4332' }}>No contracts yet</h3>
                      <p className="text-sm mb-4 max-w-xs" style={{ color: '#6B7280' }}>Generate your first contract in under 2 minutes.</p>
                      <button
                        onClick={() => navigate('new-contract')}
                        className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white transition-opacity hover:opacity-90"
                        style={{ backgroundColor: '#2D6A4F' }}
                      >
                        <Plus className="w-4 h-4" /> Create contract
                      </button>
                    </div>
                  ) : (
                    <div className="border" style={{ borderColor: '#E5E5E2' }}>
                      {savedContracts.slice(0, 5).map((c, i) => (
                        <button key={c.id} onClick={() => { setViewingContractId(c.id); setActiveTab('contract-view') }} className={cn('w-full flex items-center gap-4 px-4 py-3 hover:bg-[#FAFAF8] transition-colors text-left', i !== 0 && 'border-t')} style={{ borderColor: '#E5E5E2' }}>
                          <FileText className="w-4 h-4 flex-shrink-0" style={{ color: '#9CA3AF' }} />
                          <div className="flex-1 min-w-0">
                            <p className="text-sm font-medium truncate" style={{ color: '#1B4332' }}>{c.title}</p>
                            <p className="text-xs" style={{ color: '#9CA3AF' }}>{c.typeName}</p>
                          </div>
                          <StatusBadge status={c.status} />
                          <span className="text-xs flex-shrink-0 hidden sm:block" style={{ color: '#9CA3AF' }}>{fmtDate(c.createdAt)}</span>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </motion.div>
            )}

            {/* ── NEW CONTRACT ── */}
            {activeTab === 'new-contract' && (
              <motion.div key="new-contract" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">

                {/* Step 1: Choose type */}
                {step === 1 && (
                  <div>
                    <h1 className="font-display text-2xl font-bold mb-1" style={{ color: '#1B4332' }}>New contract</h1>
                    <p className="text-sm mb-6" style={{ color: '#6B7280' }}>Choose a contract type to get started.</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                      {CONTRACT_TYPES.map((type) => {
                        const Icon = type.Icon
                        return (
                          <button
                            key={type.id}
                            onClick={() => handleSelectType(type)}
                            className="flex flex-col items-start p-4 border text-left transition-all hover:border-[#2D6A4F] hover:bg-[#FAFAF8] group"
                            style={{ borderColor: '#E5E5E2', backgroundColor: '#FFFFFF' }}
                          >
                            <div className="w-9 h-9 flex items-center justify-center mb-3" style={{ backgroundColor: '#D8F3DC' }}>
                              <Icon className="w-4 h-4" style={{ color: '#2D6A4F' }} />
                            </div>
                            <span className="text-sm font-semibold mb-1 leading-snug" style={{ color: '#1B4332' }}>{type.title}</span>
                            <span className="text-xs leading-relaxed" style={{ color: '#6B7280' }}>{type.description}</span>
                          </button>
                        )
                      })}
                    </div>
                  </div>
                )}

                {/* Step 2: Intake Wizard */}
                {step === 2 && selectedType && (
                  <IntakeWizard
                    contractTypeId={selectedType.id}
                    contractTypeTitle={selectedType.title}
                    onComplete={handleGenerate}
                    onBack={() => setStep(1)}
                  />
                )}

                {/* Step 3: Loading */}
                {step === 3 && (
                  <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
                    <motion.div animate={{ rotate: 360 }} transition={{ duration: 1.2, repeat: Infinity, ease: 'linear' }} className="mb-6">
                      <Loader2 className="w-10 h-10" style={{ color: '#2D6A4F' }} />
                    </motion.div>
                    <AnimatePresence mode="wait">
                      <motion.p key={loadingMsg} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: 0.25 }} className="font-display text-xl font-bold mb-2" style={{ color: '#1B4332' }}>
                        {LOADING_MESSAGES[loadingMsg]}
                      </motion.p>
                    </AnimatePresence>
                    <p className="text-sm mb-6" style={{ color: '#6B7280' }}>ClauseKit is generating your bespoke UK contract&hellip;</p>
                    <div className="w-56 overflow-hidden h-1" style={{ backgroundColor: '#E5E5E2' }}>
                      <motion.div className="h-full" style={{ backgroundColor: '#2D6A4F' }} initial={{ width: '5%' }} animate={{ width: '90%' }} transition={{ duration: 6, ease: 'easeInOut' }} />
                    </div>
                    <p className="text-xs mt-4" style={{ color: '#9CA3AF' }}>Usually takes 20&ndash;40 seconds</p>
                  </div>
                )}

                {/* Step 4: Preview + Paywall */}
                {step === 4 && contractContent && (
                  <div className="max-w-2xl">
                    {/* Header */}
                    <div className="flex items-start justify-between mb-6 gap-4">
                      <div>
                        <div className="inline-flex items-center gap-1.5 px-2 py-0.5 text-xs font-semibold mb-2" style={{ backgroundColor: '#D8F3DC', color: '#1B4332' }}>
                          <Check className="w-3 h-3" style={{ color: '#2D6A4F' }} /> Generated
                        </div>
                        <h1 className="font-display text-2xl font-bold" style={{ color: '#1B4332' }}>{contractTitle ?? 'Your Contract'}</h1>
                        <p className="text-sm" style={{ color: '#6B7280' }}>UK law &middot; {selectedType?.title}</p>
                      </div>
                      <button onClick={handleReset} className="flex-shrink-0 text-xs font-medium px-3 py-1.5 border hover:opacity-70 transition-opacity" style={{ borderColor: '#E5E5E2', color: '#6B7280' }}>
                        Start over
                      </button>
                    </div>

                    {/* What you get callout */}
                    <div className="border p-4 mb-5 flex gap-4" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                      <div className="flex-1 space-y-1.5">
                        {['Full UK-compliant contract', 'PDF ready to sign', 'Editable Word (.docx)', 'IR35 &amp; GDPR clauses included'].map((f) => (
                          <div key={f} className="flex items-center gap-2 text-sm">
                            <Check className="w-3.5 h-3.5 flex-shrink-0" style={{ color: '#52B788' }} strokeWidth={3} />
                            <span dangerouslySetInnerHTML={{ __html: f }} style={{ color: '#374151' }} />
                          </div>
                        ))}
                      </div>
                      <div className="flex-shrink-0 text-right">
                        <p className="font-display text-3xl font-bold" style={{ color: '#1B4332' }}>&pound;7</p>
                        <p className="text-xs" style={{ color: '#9CA3AF' }}>one-time</p>
                      </div>
                    </div>

                    {/* Document preview with blur */}
                    <div className="border overflow-hidden relative mb-4" style={{ borderColor: '#E5E5E2', backgroundColor: '#FFFFFF' }}>
                      {/* Visible preview */}
                      <div className="px-6 pt-6 pb-2">
                        <pre className="text-xs leading-relaxed font-mono whitespace-pre-wrap" style={{ color: '#1A1A1A' }}>
                          {contractContent.slice(0, 500)}
                        </pre>
                      </div>

                      {/* Blurred section */}
                      <div className="relative">
                        <div className="px-6 pt-2 pb-6" style={{ filter: 'blur(4px)', userSelect: 'none', pointerEvents: 'none' }}>
                          <pre className="text-xs leading-relaxed font-mono whitespace-pre-wrap" style={{ color: '#1A1A1A' }}>
                            {contractContent.slice(500, 1300)}
                          </pre>
                        </div>

                        {/* Paywall overlay */}
                        <div
                          className="absolute inset-0 flex flex-col items-center justify-center text-center px-6"
                          style={{ background: 'linear-gradient(to bottom, transparent 0%, rgba(255,255,255,0.9) 30%, rgba(255,255,255,0.98) 60%)' }}
                        >
                          <div className="w-10 h-10 flex items-center justify-center mb-3" style={{ backgroundColor: '#D8F3DC' }}>
                            <Eye className="w-5 h-5" style={{ color: '#2D6A4F' }} />
                          </div>
                          <h3 className="font-display text-base font-bold mb-1" style={{ color: '#1B4332' }}>Your contract is ready</h3>
                          <p className="text-sm mb-5 max-w-xs" style={{ color: '#6B7280' }}>
                            Unlock the full contract &mdash; download as PDF and Word, ready to sign and send.
                          </p>
                          <button
                            onClick={handleCheckout}
                            disabled={checkoutLoading}
                            className="inline-flex items-center gap-2 px-6 py-3 text-sm font-semibold text-white transition-opacity hover:opacity-90 disabled:opacity-60 mb-2"
                            style={{ backgroundColor: '#2D6A4F' }}
                          >
                            {checkoutLoading ? (
                              <><Loader2 className="w-4 h-4 animate-spin" /> Redirecting to payment&hellip;</>
                            ) : (
                              <><Download className="w-4 h-4" /> &pound;7 &mdash; Unlock full contract (PDF + Word)</>
                            )}
                          </button>
                          <p className="text-xs" style={{ color: '#9CA3AF' }}>Secure payment via Stripe &middot; Instant download</p>
                        </div>
                      </div>
                    </div>

                    <div className="text-center">
                      <a href={`/preview/${contractId}`} className="inline-flex items-center gap-1.5 text-sm font-medium hover:opacity-70 transition-opacity" style={{ color: '#2D6A4F' }}>
                        View full preview page <ExternalLink className="w-3.5 h-3.5" />
                      </a>
                    </div>
                  </div>
                )}
              </motion.div>
            )}

            {/* ── MY CONTRACTS ── */}
            {activeTab === 'my-contracts' && (
              <MyContractsTab
                savedContracts={savedContracts}
                searchQuery={searchQuery}
                onNew={() => navigate('new-contract')}
                onCheckout={initiateCheckout}
                onView={(id) => { setViewingContractId(id); setActiveTab('contract-view') }}
              />
            )}

            {/* ── TEMPLATES ── */}
            {activeTab === 'templates' && (
              <motion.div key="templates" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
                <div className="mb-6">
                  <h1 className="font-display text-2xl font-bold mb-1" style={{ color: '#1B4332' }}>Contract templates</h1>
                  <p className="text-sm" style={{ color: '#6B7280' }}>8 UK-compliant contract templates. Click any to generate instantly.</p>
                </div>

                <div className="border" style={{ borderColor: '#E5E5E2' }}>
                  <div className="flex items-center gap-4 px-4 py-2.5 border-b text-xs font-bold uppercase tracking-widest" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8', color: '#9CA3AF' }}>
                    <div className="flex-1">Template</div>
                    <div className="w-56 hidden lg:block">Description</div>
                    <div className="w-24 text-right">Action</div>
                  </div>
                  {CONTRACT_TYPES.map((type, i) => {
                    const Icon = type.Icon
                    return (
                      <div key={type.id} className={cn('flex items-center gap-4 px-4 py-4 hover:bg-[#FAFAF8] transition-colors', i !== 0 && 'border-t')} style={{ borderColor: '#E5E5E2' }}>
                        <div className="w-9 h-9 flex items-center justify-center flex-shrink-0" style={{ backgroundColor: '#D8F3DC' }}>
                          <Icon className="w-4 h-4" style={{ color: '#2D6A4F' }} />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold" style={{ color: '#1B4332' }}>{type.title}</p>
                        </div>
                        <div className="w-56 hidden lg:block">
                          <p className="text-xs truncate" style={{ color: '#6B7280' }}>{type.description}</p>
                        </div>
                        <div className="w-24 text-right">
                          <button onClick={() => handleSelectType(type)} className="text-xs font-semibold flex items-center gap-1 ml-auto hover:opacity-70 transition-opacity" style={{ color: '#2D6A4F' }}>
                            Generate <ArrowRight className="w-3 h-3" />
                          </button>
                        </div>
                      </div>
                    )
                  })}
                </div>

                <div className="mt-6 border p-4 flex items-center gap-4" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                  <Zap className="w-5 h-5 flex-shrink-0" style={{ color: '#2D6A4F' }} />
                  <div className="flex-1">
                    <p className="text-sm font-semibold" style={{ color: '#1B4332' }}>All templates included in both plans</p>
                    <p className="text-xs" style={{ color: '#6B7280' }}>Pay &pound;7 per contract, or &pound;19/month for unlimited access to every template.</p>
                  </div>
                  <button onClick={() => navigate('pricing')} className="flex-shrink-0 text-xs font-semibold hover:opacity-70 transition-opacity" style={{ color: '#2D6A4F' }}>
                    See pricing &rarr;
                  </button>
                </div>
              </motion.div>
            )}

            {/* ── PRICING ── */}
            {activeTab === 'pricing' && (
              <motion.div key="pricing" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
                <div className="mb-6">
                  <h1 className="font-display text-2xl font-bold mb-1" style={{ color: '#1B4332' }}>Pricing</h1>
                  <p className="text-sm" style={{ color: '#6B7280' }}>Generate for free. Pay only when you download.</p>
                </div>

                <div className="grid sm:grid-cols-2 gap-5 max-w-2xl mb-6">
                  {/* Pay per doc */}
                  <div className="border-2 p-7" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                    <p className="text-xs font-bold uppercase tracking-widest mb-4" style={{ color: '#9CA3AF' }}>Pay as you go</p>
                    <div className="flex items-baseline gap-1 mb-1">
                      <span className="font-display text-5xl font-bold" style={{ color: '#1B4332' }}>&pound;7</span>
                      <span className="text-sm" style={{ color: '#6B7280' }}>/ contract</span>
                    </div>
                    <p className="text-sm mb-6" style={{ color: '#6B7280' }}>Generate and download one contract at a time.</p>
                    <ul className="space-y-2.5 mb-7">
                      {['Full UK-compliant contract', 'PDF + Word download', 'Tailored to your answers', 'No subscription needed'].map((f) => (
                        <li key={f} className="flex items-center gap-2.5 text-sm">
                          <Check className="w-4 h-4 flex-shrink-0" style={{ color: '#52B788' }} strokeWidth={3} />
                          <span style={{ color: '#1A1A1A' }}>{f}</span>
                        </li>
                      ))}
                    </ul>
                    <button onClick={() => navigate('new-contract')} className="w-full py-2.5 text-sm font-semibold border-2 transition-colors hover:bg-[#D8F3DC]" style={{ borderColor: '#2D6A4F', color: '#2D6A4F', backgroundColor: 'transparent' }}>
                      Generate a contract
                    </button>
                  </div>

                  {/* Unlimited */}
                  <div className="border-2 p-7 relative text-white" style={{ borderColor: '#2D6A4F', backgroundColor: '#2D6A4F' }}>
                    <div className="absolute -top-3.5 left-5 px-3 py-0.5 text-xs font-bold" style={{ backgroundColor: '#52B788', color: '#1B4332' }}>Best value</div>
                    <p className="text-xs font-bold uppercase tracking-widest mb-4" style={{ color: '#D8F3DC' }}>Unlimited</p>
                    <div className="flex items-baseline gap-1 mb-1">
                      <span className="font-display text-5xl font-bold">&pound;19</span>
                      <span className="text-sm" style={{ color: '#D8F3DC' }}>/month</span>
                    </div>
                    <p className="text-sm mb-6" style={{ color: '#D8F3DC' }}>Unlimited contracts for busy freelancers and teams.</p>
                    <ul className="space-y-2.5 mb-7">
                      {['All 8 contract types', 'Unlimited downloads', 'PDF + Word', 'Cancel any time'].map((f) => (
                        <li key={f} className="flex items-center gap-2.5 text-sm">
                          <Check className="w-4 h-4 flex-shrink-0" style={{ color: '#52B788' }} strokeWidth={3} />
                          <span>{f}</span>
                        </li>
                      ))}
                    </ul>
                    <button className="w-full py-2.5 text-sm font-semibold transition-opacity hover:opacity-90" style={{ backgroundColor: '#FFFFFF', color: '#1B4332' }}>
                      Get unlimited access
                    </button>
                  </div>
                </div>

                <div className="max-w-2xl border p-4 flex items-start gap-3" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                  <Star className="w-4 h-4 flex-shrink-0 mt-0.5 fill-current" style={{ color: '#F59E0B' }} />
                  <p className="text-sm" style={{ color: '#6B7280' }}>
                    A solicitor charges &pound;150&ndash;&pound;500 for the same document. One ClauseKit contract pays for 3 months of the unlimited plan. &middot; Secure payments via Stripe.
                  </p>
                </div>
              </motion.div>
            )}

            {/* ── HELP ── */}
            {activeTab === 'help' && (
              <motion.div key="help" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
                <div className="mb-6">
                  <h1 className="font-display text-2xl font-bold mb-1" style={{ color: '#1B4332' }}>Help &amp; FAQ</h1>
                  <p className="text-sm" style={{ color: '#6B7280' }}>Frequently asked questions about ClauseKit.</p>
                </div>

                {/* Trust strip */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8">
                  {[
                    { Icon: Shield, label: 'Solicitor-Reviewed' },
                    { Icon: Zap, label: 'ClauseKit Powered' },
                    { Icon: FileText, label: 'UK Law Only' },
                    { Icon: Lock, label: 'GDPR Compliant' },
                  ].map((t) => (
                    <div key={t.label} className="flex items-center gap-2.5 border p-3" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                      <t.Icon className="w-4 h-4 flex-shrink-0" style={{ color: '#2D6A4F' }} />
                      <span className="text-xs font-semibold" style={{ color: '#1B4332' }}>{t.label}</span>
                    </div>
                  ))}
                </div>

                <div className="max-w-2xl border" style={{ borderColor: '#E5E5E2', backgroundColor: '#FFFFFF' }}>
                  <div className="px-6 divide-y" style={{ borderColor: '#E5E5E2' }}>
                    {FAQS.map((item) => <FaqItem key={item.q} q={item.q} a={item.a} />)}
                  </div>
                </div>

                <div className="max-w-2xl mt-5 border p-5 flex items-center gap-4" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                  <div className="w-10 h-10 flex items-center justify-center flex-shrink-0" style={{ backgroundColor: '#25D366' }}>
                    <svg className="w-5 h-5 text-white" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
                    </svg>
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-semibold mb-0.5" style={{ color: '#1B4332' }}>Still have a question?</p>
                    <p className="text-xs" style={{ color: '#6B7280' }}>Message us on WhatsApp. We usually reply within an hour.</p>
                  </div>
                  <a href="https://wa.me/447700900000" target="_blank" rel="noreferrer" className="flex-shrink-0 px-4 py-2 text-xs font-semibold text-white transition-opacity hover:opacity-90" style={{ backgroundColor: '#25D366' }}>
                    Chat with us
                  </a>
                </div>
              </motion.div>
            )}

            {/* ── CONTRACT VIEW ── */}
            {activeTab === 'contract-view' && viewingContractId && (() => {
              const c = savedContracts.find(s => s.id === viewingContractId)
              if (!c) return (
                <motion.div key="contract-view-empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="p-8">
                  <p className="text-sm" style={{ color: '#6B7280' }}>Contract not found.</p>
                </motion.div>
              )
              return (
                <motion.div key={`contract-view-${c.id}`} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="h-full overflow-hidden">
                  <ContractViewer
                    contract={c}
                    onBack={() => { setActiveTab('my-contracts'); setViewingContractId(null) }}
                    onCheckout={initiateCheckout}
                    onUpdate={(updated) => {
                      const next = savedContracts.map(s => s.id === updated.id ? updated : s)
                      setSavedContracts(next)
                      persistSaved(next)
                    }}
                  />
                </motion.div>
              )
            })()}

          </AnimatePresence>
        </main>
      </div>
      </div>
    </div>
  )
}
