'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Link from 'next/link'
import { cn } from '@/lib/utils'
import {
  Plus,
  FileText,
  Home,
  LayoutTemplate,
  CreditCard,
  HelpCircle,
  Briefcase,
  Users,
  Lock,
  RotateCcw,
  Wrench,
  ClipboardList,
  Globe,
  Shield,
  ArrowRight,
  ArrowLeft,
  Check,
  Loader2,
  Eye,
  Download,
  ExternalLink,
  Search,
  LogOut,
  Menu,
  X,
  ChevronDown,
  Zap,
  Star,
  AlertCircle,
} from 'lucide-react'

// ── Types ──────────────────────────────────────────────────────────────────────

type Tab = 'home' | 'new-contract' | 'my-contracts' | 'templates' | 'pricing' | 'help'
type Step = 1 | 2 | 3 | 4

interface ContractType {
  id: string
  title: string
  description: string
  Icon: React.ComponentType<{ className?: string; style?: React.CSSProperties }>
}

interface FormData {
  description: string
  party1: string
  party2: string
  value: string
  governingLaw: string
}

interface SavedContract {
  id: string
  title: string
  typeId: string
  typeName: string
  party1: string
  party2: string
  status: 'generated' | 'paid'
  createdAt: string
}

// ── Data ───────────────────────────────────────────────────────────────────────

const CONTRACT_TYPES: ContractType[] = [
  { id: 'freelance', title: 'Freelance / Project Agreement', description: 'Scope, deliverables, payment terms and IP ownership.', Icon: Briefcase },
  { id: 'nda-mutual', title: 'NDA (Mutual)', description: 'Both parties protect each other\'s confidential information.', Icon: Users },
  { id: 'nda-one-way', title: 'NDA (One-Way)', description: 'One party discloses; the other agrees to protect it.', Icon: Lock },
  { id: 'retainer', title: 'Retainer Agreement', description: 'Ongoing services with a fixed monthly fee.', Icon: RotateCcw },
  { id: 'subcontractor', title: 'Subcontractor Agreement', description: 'Third-party contractor terms for client work.', Icon: Wrench },
  { id: 'client-service', title: 'Client Service Agreement', description: 'General terms for providing services to clients.', Icon: ClipboardList },
  { id: 'website-tcs', title: 'Website T&Cs', description: 'Terms, privacy policy and acceptable use for websites.', Icon: Globe },
  { id: 'employment-offer', title: 'Employment Offer Letter', description: 'Offer of employment with role, salary and conditions.', Icon: Shield },
]

const SIDEBAR_NAV: { id: Tab; label: string; Icon: React.ComponentType<{ className?: string; style?: React.CSSProperties }> }[] = [
  { id: 'home', label: 'Home', Icon: Home },
  { id: 'new-contract', label: 'New Contract', Icon: Plus },
  { id: 'my-contracts', label: 'My Contracts', Icon: FileText },
  { id: 'templates', label: 'Templates', Icon: LayoutTemplate },
  { id: 'pricing', label: 'Pricing', Icon: CreditCard },
  { id: 'help', label: 'Help', Icon: HelpCircle },
]

const LOADING_MESSAGES = [
  'Drafting your contract\u2026',
  'Applying UK legal clauses\u2026',
  'Checking IR35 compliance\u2026',
  'Finalising your document\u2026',
]

const LS_KEY = 'clausekit_contracts'

function loadSaved(): SavedContract[] {
  if (typeof window === 'undefined') return []
  try { return JSON.parse(localStorage.getItem(LS_KEY) ?? '[]') } catch { return [] }
}
function persistSaved(c: SavedContract[]) {
  if (typeof window !== 'undefined') localStorage.setItem(LS_KEY, JSON.stringify(c))
}

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

// ── FAQ data ───────────────────────────────────────────────────────────────────

const FAQS = [
  { q: 'Are ClauseKit contracts legally binding?', a: 'Yes. Contracts generated by ClauseKit are legally binding when properly executed by both parties. They are drafted to comply with UK law. For high-value or complex matters, we recommend review by a qualified solicitor.' },
  { q: 'What happens after I generate a contract?', a: 'You\u2019ll see a preview of your contract immediately. To download the full PDF and Word versions, you pay a one-time \u00A37 fee via Stripe. Your contract is available for instant download.' },
  { q: 'Can I edit the contract after downloading?', a: 'Yes \u2014 the Word (.docx) version is fully editable. Make any adjustments before sending to the other party.' },
  { q: 'Is my data secure?', a: 'We don\u2019t store your contract content after generation. Payments are processed securely by Stripe. We never share your data with third parties.' },
  { q: 'What if I need a contract type that isn\u2019t listed?', a: 'Use the \u201cClient Service Agreement\u201d or \u201cFreelance / Project Agreement\u201d types \u2014 they cover most situations. Describe your exact needs in the description field and ClauseKit will tailor accordingly.' },
]

// ── Sub-components ─────────────────────────────────────────────────────────────

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="border-b last:border-b-0" style={{ borderColor: '#E5E5E2' }}>
      <button className="w-full flex items-center justify-between py-4 text-left" onClick={() => setOpen(!open)}>
        <span className="text-sm font-semibold pr-4" style={{ color: '#1B4332' }}>{q}</span>
        <motion.div animate={{ rotate: open ? 180 : 0 }} transition={{ duration: 0.2 }}>
          <ChevronDown className="w-4 h-4 flex-shrink-0" style={{ color: '#6B7280' }} />
        </motion.div>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22 }}
            className="overflow-hidden"
          >
            <p className="pb-4 text-sm leading-relaxed" style={{ color: '#6B7280' }}>{a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

// ── Checkout helper ────────────────────────────────────────────────────────────

async function initiateCheckout(contractId: string): Promise<void> {
  const res = await fetch('/api/checkout', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ contractId }),
  })
  const data = await res.json()
  if (data.url) {
    window.location.href = data.url
  } else {
    throw new Error(data.error ?? 'Checkout failed')
  }
}

// ── Page ───────────────────────────────────────────────────────────────────────

export default function AppDashboard() {
  const [activeTab, setActiveTab] = useState<Tab>('home')
  const [step, setStep] = useState<Step>(1)
  const [selectedType, setSelectedType] = useState<ContractType | null>(null)
  const [formData, setFormData] = useState<FormData>({
    description: '', party1: '', party2: '', value: '', governingLaw: 'England & Wales',
  })
  const [loadingMsg, setLoadingMsg] = useState(0)
  const [contractId, setContractId] = useState<string | null>(null)
  const [contractContent, setContractContent] = useState<string | null>(null)
  const [contractTitle, setContractTitle] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [checkoutLoading, setCheckoutLoading] = useState(false)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [savedContracts, setSavedContracts] = useState<SavedContract[]>([])
  const [searchQuery, setSearchQuery] = useState('')

  useEffect(() => { setSavedContracts(loadSaved()) }, [])

  // Loading message cycle
  useEffect(() => {
    if (step !== 3) return
    const t = setInterval(() => setLoadingMsg((v) => Math.min(v + 1, LOADING_MESSAGES.length - 1)), 1800)
    return () => clearInterval(t)
  }, [step])

  const navigate = (tab: Tab) => {
    setActiveTab(tab)
    setSidebarOpen(false)
    if (tab === 'new-contract') handleReset()
  }

  const handleSelectType = (type: ContractType) => {
    setSelectedType(type)
    setStep(2)
    setActiveTab('new-contract')
  }

  const handleGenerate = async () => {
    if (!selectedType) return
    setError(null)
    setLoadingMsg(0)
    setStep(3)
    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contractType: selectedType.id,
          customDescription: formData.description,
          fields: {
            party1Name: formData.party1,
            party2Name: formData.party2,
            value: formData.value,
            governingLaw: formData.governingLaw,
          },
        }),
      })
      if (!res.ok) {
        const body = await res.json().catch(() => ({}))
        throw new Error(body.error ?? 'Generation failed')
      }
      const data = await res.json()
      // API returns contractId (not id)
      const id = data.contractId ?? data.id
      setContractId(id)
      setContractContent(data.content)
      setContractTitle(data.title)
      setStep(4)

      // Persist to localStorage
      const entry: SavedContract = {
        id,
        title: data.title ?? selectedType.title,
        typeId: selectedType.id,
        typeName: selectedType.title,
        party1: formData.party1,
        party2: formData.party2,
        status: 'generated',
        createdAt: new Date().toISOString(),
      }
      const updated = [entry, ...loadSaved()]
      persistSaved(updated)
      setSavedContracts(updated)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Something went wrong')
      setStep(2)
    }
  }

  const handleCheckout = async () => {
    if (!contractId) return
    setCheckoutLoading(true)
    try {
      await initiateCheckout(contractId)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Checkout failed')
      setCheckoutLoading(false)
    }
  }

  const handleReset = () => {
    setStep(1)
    setSelectedType(null)
    setFormData({ description: '', party1: '', party2: '', value: '', governingLaw: 'England & Wales' })
    setContractId(null)
    setContractContent(null)
    setContractTitle(null)
    setError(null)
    setLoadingMsg(0)
    setCheckoutLoading(false)
  }

  const stats = {
    total: savedContracts.length,
    generated: savedContracts.filter((c) => c.status === 'generated').length,
    paid: savedContracts.filter((c) => c.status === 'paid').length,
  }

  const filtered = savedContracts.filter((c) =>
    c.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    c.typeName.toLowerCase().includes(searchQuery.toLowerCase())
  )

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="flex h-screen overflow-hidden" style={{ backgroundColor: '#FAFAF8' }}>

      {/* ── SIDEBAR ── */}
      <aside
        className={cn(
          'flex-shrink-0 flex flex-col h-full z-40 transition-transform duration-200',
          'w-[220px] border-r',
          'max-md:fixed max-md:top-0 max-md:left-0 max-md:shadow-xl',
          sidebarOpen ? 'max-md:translate-x-0' : 'max-md:-translate-x-full',
        )}
        style={{ backgroundColor: '#FFFFFF', borderColor: '#E5E5E2' }}
      >
        {/* Logo */}
        <div className="px-5 h-12 flex items-center border-b flex-shrink-0" style={{ borderColor: '#E5E5E2' }}>
          <Link href="/" className="flex items-center gap-2">
            <div className="w-6 h-6 flex items-center justify-center" style={{ backgroundColor: '#2D6A4F' }}>
              <FileText className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-bold text-sm tracking-tight" style={{ color: '#1B4332' }}>ClauseKit</span>
          </Link>
        </div>

        {/* Nav */}
        <nav className="flex-1 py-2 overflow-y-auto">
          {SIDEBAR_NAV.map((item) => {
            const Icon = item.Icon
            const isActive = activeTab === item.id
            return (
              <button
                key={item.id}
                onClick={() => navigate(item.id)}
                className={cn(
                  'w-full flex items-center gap-3 px-4 py-2.5 text-sm font-medium transition-all text-left border-l-2',
                  isActive ? '' : 'hover:bg-[#FAFAF8] border-l-transparent',
                )}
                style={isActive ? { backgroundColor: '#EDFAF2', color: '#1B4332', borderLeftColor: '#2D6A4F' } : { color: '#6B7280' }}
              >
                <Icon className="w-4 h-4 flex-shrink-0" style={{ color: isActive ? '#2D6A4F' : '#9CA3AF' }} />
                {item.label}
              </button>
            )
          })}
        </nav>

        {/* Upgrade nudge */}
        <div className="mx-3 mb-3 p-3 border" style={{ backgroundColor: '#EDFAF2', borderColor: '#52B78840' }}>
          <p className="text-xs font-semibold mb-0.5" style={{ color: '#1B4332' }}>Unlimited access</p>
          <p className="text-xs mb-2" style={{ color: '#52B788' }}>&pound;19/mo &mdash; all types, unlimited</p>
          <button
            onClick={() => navigate('pricing')}
            className="w-full py-1.5 text-xs font-semibold text-white transition-opacity hover:opacity-90"
            style={{ backgroundColor: '#2D6A4F' }}
          >
            Upgrade
          </button>
        </div>

        {/* Footer */}
        <div className="border-t flex-shrink-0" style={{ borderColor: '#E5E5E2' }}>
          <Link href="/" className="w-full flex items-center gap-3 px-4 py-3 text-sm font-medium hover:bg-[#FAFAF8] transition-colors" style={{ color: '#6B7280' }}>
            <LogOut className="w-4 h-4" style={{ color: '#9CA3AF' }} />
            Back to site
          </Link>
        </div>
      </aside>

      {/* Mobile overlay */}
      {sidebarOpen && <div className="md:hidden fixed inset-0 z-30 bg-black/20" onClick={() => setSidebarOpen(false)} />}

      {/* ── MAIN ── */}
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">

        {/* Top bar */}
        <div className="flex items-center gap-3 px-4 h-12 border-b flex-shrink-0 bg-white" style={{ borderColor: '#E5E5E2' }}>
          <button className="md:hidden p-1 text-gray-500" onClick={() => setSidebarOpen(!sidebarOpen)} aria-label="Menu">
            {sidebarOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
          </button>

          {/* Search */}
          <div className="flex-1 flex items-center gap-2 border px-3 py-1.5 max-w-md" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
            <Search className="w-3.5 h-3.5 flex-shrink-0" style={{ color: '#9CA3AF' }} />
            <input
              type="text"
              placeholder="Search contracts..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="text-sm bg-transparent outline-none w-full placeholder-gray-400"
              style={{ color: '#1A1A1A' }}
            />
          </div>

          <div className="ml-auto flex items-center gap-2">
            <button
              onClick={() => navigate('new-contract')}
              className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 text-sm font-semibold text-white transition-opacity hover:opacity-90"
              style={{ backgroundColor: '#2D6A4F' }}
            >
              <Plus className="w-3.5 h-3.5" />
              New Contract
            </button>
            <div className="w-7 h-7 flex items-center justify-center text-xs font-bold text-white" style={{ backgroundColor: '#2D6A4F' }}>
              JW
            </div>
          </div>
        </div>

        {/* Content */}
        <main className="flex-1 overflow-y-auto bg-white">
          <AnimatePresence mode="wait">

            {/* ── HOME ── */}
            {activeTab === 'home' && (
              <motion.div key="home" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <h1 className="font-display text-2xl font-bold" style={{ color: '#1B4332' }}>Welcome back</h1>
                    <p className="text-sm mt-0.5" style={{ color: '#6B7280' }}>Generate a UK-compliant contract in under 2 minutes.</p>
                  </div>
                  <button
                    onClick={() => navigate('new-contract')}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white transition-opacity hover:opacity-90"
                    style={{ backgroundColor: '#2D6A4F' }}
                  >
                    <Plus className="w-4 h-4" /> New Contract
                  </button>
                </div>

                {/* Stats */}
                <div className="grid grid-cols-3 border mb-8" style={{ borderColor: '#E5E5E2' }}>
                  {[
                    { label: 'Contracts generated', value: stats.total },
                    { label: 'Awaiting download', value: stats.generated },
                    { label: 'Downloaded', value: stats.paid },
                  ].map((s, i) => (
                    <div key={i} className={cn('p-4', i !== 2 && 'border-r')} style={{ borderColor: '#E5E5E2' }}>
                      <p className="text-xs font-medium mb-1" style={{ color: '#9CA3AF' }}>{s.label}</p>
                      <p className="font-display text-2xl font-bold" style={{ color: '#1B4332' }}>{s.value}</p>
                    </div>
                  ))}
                </div>

                {/* Quick-start contract types */}
                <div className="mb-8">
                  <h2 className="text-xs font-bold uppercase tracking-widest mb-3" style={{ color: '#9CA3AF' }}>Quick start</h2>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                    {CONTRACT_TYPES.slice(0, 4).map((c) => {
                      const Icon = c.Icon
                      return (
                        <button
                          key={c.id}
                          onClick={() => handleSelectType(c)}
                          className="flex items-center gap-3 p-3 border text-left hover:border-[#2D6A4F] hover:bg-[#FAFAF8] transition-all"
                          style={{ borderColor: '#E5E5E2', backgroundColor: '#FFFFFF' }}
                        >
                          <div className="w-8 h-8 flex items-center justify-center flex-shrink-0" style={{ backgroundColor: '#D8F3DC' }}>
                            <Icon className="w-4 h-4" style={{ color: '#2D6A4F' }} />
                          </div>
                          <span className="text-xs font-semibold leading-snug" style={{ color: '#1B4332' }}>{c.title}</span>
                        </button>
                      )
                    })}
                  </div>
                </div>

                {/* Recent contracts */}
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <h2 className="text-xs font-bold uppercase tracking-widest" style={{ color: '#9CA3AF' }}>Recent contracts</h2>
                    {savedContracts.length > 0 && (
                      <button onClick={() => navigate('my-contracts')} className="text-xs font-medium hover:opacity-70" style={{ color: '#2D6A4F' }}>
                        View all
                      </button>
                    )}
                  </div>

                  {savedContracts.length === 0 ? (
                    <div className="flex flex-col items-center justify-center py-16 text-center border" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                      <div className="w-12 h-12 flex items-center justify-center mb-4" style={{ backgroundColor: '#D8F3DC' }}>
                        <FileText className="w-6 h-6" style={{ color: '#2D6A4F' }} />
                      </div>
                      <h3 className="font-display text-base font-bold mb-2" style={{ color: '#1B4332' }}>No contracts yet</h3>
                      <p className="text-sm mb-4 max-w-xs" style={{ color: '#6B7280' }}>Generate your first contract in under 2 minutes.</p>
                      <button
                        onClick={() => navigate('new-contract')}
                        className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white transition-opacity hover:opacity-90"
                        style={{ backgroundColor: '#2D6A4F' }}
                      >
                        <Plus className="w-4 h-4" /> Create contract
                      </button>
                    </div>
                  ) : (
                    <div className="border" style={{ borderColor: '#E5E5E2' }}>
                      {savedContracts.slice(0, 5).map((c, i) => (
                        <div key={c.id} className={cn('flex items-center gap-4 px-4 py-3 hover:bg-[#FAFAF8] transition-colors', i !== 0 && 'border-t')} style={{ borderColor: '#E5E5E2' }}>
                          <FileText className="w-4 h-4 flex-shrink-0" style={{ color: '#9CA3AF' }} />
                          <div className="flex-1 min-w-0">
                            <p className="text-sm font-medium truncate" style={{ color: '#1B4332' }}>{c.title}</p>
                            <p className="text-xs" style={{ color: '#9CA3AF' }}>{c.typeName}</p>
                          </div>
                          <span
                            className="text-xs font-bold px-2 py-0.5 uppercase tracking-wide flex-shrink-0"
                            style={c.status === 'paid' ? { backgroundColor: '#D8F3DC', color: '#1B4332' } : { backgroundColor: '#FEF3C7', color: '#92400E' }}
                          >
                            {c.status === 'paid' ? 'Downloaded' : 'Generated'}
                          </span>
                          <span className="text-xs flex-shrink-0 hidden sm:block" style={{ color: '#9CA3AF' }}>{fmtDate(c.createdAt)}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </motion.div>
            )}

            {/* ── NEW CONTRACT ── */}
            {activeTab === 'new-contract' && (
              <motion.div key="new-contract" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">

                {/* Step 1: Choose type */}
                {step === 1 && (
                  <div>
                    <h1 className="font-display text-2xl font-bold mb-1" style={{ color: '#1B4332' }}>New contract</h1>
                    <p className="text-sm mb-6" style={{ color: '#6B7280' }}>Choose a contract type to get started.</p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                      {CONTRACT_TYPES.map((type) => {
                        const Icon = type.Icon
                        return (
                          <button
                            key={type.id}
                            onClick={() => handleSelectType(type)}
                            className="flex flex-col items-start p-4 border text-left transition-all hover:border-[#2D6A4F] hover:bg-[#FAFAF8] group"
                            style={{ borderColor: '#E5E5E2', backgroundColor: '#FFFFFF' }}
                          >
                            <div className="w-9 h-9 flex items-center justify-center mb-3" style={{ backgroundColor: '#D8F3DC' }}>
                              <Icon className="w-4 h-4" style={{ color: '#2D6A4F' }} />
                            </div>
                            <span className="text-sm font-semibold mb-1 leading-snug" style={{ color: '#1B4332' }}>{type.title}</span>
                            <span className="text-xs leading-relaxed" style={{ color: '#6B7280' }}>{type.description}</span>
                          </button>
                        )
                      })}
                    </div>
                  </div>
                )}

                {/* Step 2: Details */}
                {step === 2 && selectedType && (
                  <div className="max-w-2xl">
                    <button onClick={() => setStep(1)} className="flex items-center gap-1.5 text-sm mb-6 hover:opacity-70 transition-opacity" style={{ color: '#6B7280' }}>
                      <ArrowLeft className="w-4 h-4" /> Back
                    </button>

                    <div className="mb-6">
                      <div className="inline-flex items-center gap-2 px-3 py-1 text-xs font-semibold mb-3" style={{ backgroundColor: '#D8F3DC', color: '#1B4332' }}>
                        <selectedType.Icon className="w-3.5 h-3.5" style={{ color: '#2D6A4F' }} />
                        {selectedType.title}
                      </div>
                      <h1 className="font-display text-2xl font-bold mb-1" style={{ color: '#1B4332' }}>Tell us about your contract</h1>
                      <p className="text-sm" style={{ color: '#6B7280' }}>Describe your situation in plain English &mdash; no legal knowledge needed.</p>
                    </div>

                    {error && (
                      <div className="mb-4 flex items-start gap-3 px-4 py-3 text-sm border" style={{ backgroundColor: '#FEF2F2', borderColor: '#FECACA', color: '#991B1B' }}>
                        <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
                        {error}
                      </div>
                    )}

                    <div className="space-y-4">
                      <div>
                        <label className="block text-sm font-semibold mb-1.5" style={{ color: '#1B4332' }}>
                          Describe your situation <span style={{ color: '#EF4444' }}>*</span>
                        </label>
                        <textarea
                          value={formData.description}
                          onChange={(e) => setFormData((f) => ({ ...f, description: e.target.value }))}
                          rows={5}
                          className="w-full border px-4 py-3 text-sm resize-none focus:outline-none focus:ring-1 focus:ring-[#2D6A4F]"
                          style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8', color: '#1A1A1A' }}
                          placeholder="I am a web designer based in London. My client is a restaurant group. Fixed fee of £4,500, 6-week timeline. I need protection against scope creep and want IP to transfer only on full payment."
                        />
                        <p className="text-xs mt-1" style={{ color: '#9CA3AF' }}>The more detail you provide, the better your contract will be.</p>
                      </div>

                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        {[
                          { key: 'party1', label: 'Your name / company', placeholder: 'e.g. Jane Smith / Acme Ltd' },
                          { key: 'party2', label: 'Client / other party', placeholder: 'e.g. Restaurant Group Ltd' },
                          { key: 'value', label: 'Contract value (optional)', placeholder: 'e.g. £4,500 fixed fee' },
                        ].map((field) => (
                          <div key={field.key}>
                            <label className="block text-sm font-semibold mb-1.5" style={{ color: '#1B4332' }}>{field.label}</label>
                            <input
                              type="text"
                              value={formData[field.key as keyof FormData]}
                              onChange={(e) => setFormData((f) => ({ ...f, [field.key]: e.target.value }))}
                              className="w-full border px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-[#2D6A4F]"
                              style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8', color: '#1A1A1A' }}
                              placeholder={field.placeholder}
                            />
                          </div>
                        ))}
                        <div>
                          <label className="block text-sm font-semibold mb-1.5" style={{ color: '#1B4332' }}>Governing law</label>
                          <select
                            value={formData.governingLaw}
                            onChange={(e) => setFormData((f) => ({ ...f, governingLaw: e.target.value }))}
                            className="w-full border px-4 py-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-[#2D6A4F]"
                            style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8', color: '#1A1A1A' }}
                          >
                            <option>England &amp; Wales</option>
                            <option>Scotland</option>
                            <option>Northern Ireland</option>
                          </select>
                        </div>
                      </div>

                      <button
                        onClick={handleGenerate}
                        disabled={!formData.description.trim()}
                        className="flex items-center justify-center gap-2 w-full py-3 text-sm font-semibold text-white transition-opacity hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed"
                        style={{ backgroundColor: '#2D6A4F' }}
                      >
                        Generate Contract <ArrowRight className="w-4 h-4" />
                      </button>
                      <p className="text-xs text-center" style={{ color: '#9CA3AF' }}>Free to generate &middot; Pay &pound;7 to download PDF + Word</p>
                    </div>
                  </div>
                )}

                {/* Step 3: Loading */}
                {step === 3 && (
                  <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
                    <motion.div animate={{ rotate: 360 }} transition={{ duration: 1.2, repeat: Infinity, ease: 'linear' }} className="mb-6">
                      <Loader2 className="w-10 h-10" style={{ color: '#2D6A4F' }} />
                    </motion.div>
                    <AnimatePresence mode="wait">
                      <motion.p key={loadingMsg} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} transition={{ duration: 0.25 }} className="font-display text-xl font-bold mb-2" style={{ color: '#1B4332' }}>
                        {LOADING_MESSAGES[loadingMsg]}
                      </motion.p>
                    </AnimatePresence>
                    <p className="text-sm mb-6" style={{ color: '#6B7280' }}>GPT-4o is generating your bespoke UK contract&hellip;</p>
                    <div className="w-56 overflow-hidden h-1" style={{ backgroundColor: '#E5E5E2' }}>
                      <motion.div className="h-full" style={{ backgroundColor: '#2D6A4F' }} initial={{ width: '5%' }} animate={{ width: '90%' }} transition={{ duration: 6, ease: 'easeInOut' }} />
                    </div>
                    <p className="text-xs mt-4" style={{ color: '#9CA3AF' }}>Usually takes 20&ndash;40 seconds</p>
                  </div>
                )}

                {/* Step 4: Preview + Paywall */}
                {step === 4 && contractContent && (
                  <div className="max-w-2xl">
                    {/* Header */}
                    <div className="flex items-start justify-between mb-6 gap-4">
                      <div>
                        <div className="inline-flex items-center gap-1.5 px-2 py-0.5 text-xs font-semibold mb-2" style={{ backgroundColor: '#D8F3DC', color: '#1B4332' }}>
                          <Check className="w-3 h-3" style={{ color: '#2D6A4F' }} /> Generated
                        </div>
                        <h1 className="font-display text-2xl font-bold" style={{ color: '#1B4332' }}>{contractTitle ?? 'Your Contract'}</h1>
                        <p className="text-sm" style={{ color: '#6B7280' }}>UK law &middot; {selectedType?.title}</p>
                      </div>
                      <button onClick={handleReset} className="flex-shrink-0 text-xs font-medium px-3 py-1.5 border hover:opacity-70 transition-opacity" style={{ borderColor: '#E5E5E2', color: '#6B7280' }}>
                        Start over
                      </button>
                    </div>

                    {/* What you get callout */}
                    <div className="border p-4 mb-5 flex gap-4" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                      <div className="flex-1 space-y-1.5">
                        {['Full UK-compliant contract', 'PDF ready to sign', 'Editable Word (.docx)', 'IR35 &amp; GDPR clauses included'].map((f) => (
                          <div key={f} className="flex items-center gap-2 text-sm">
                            <Check className="w-3.5 h-3.5 flex-shrink-0" style={{ color: '#52B788' }} strokeWidth={3} />
                            <span dangerouslySetInnerHTML={{ __html: f }} style={{ color: '#374151' }} />
                          </div>
                        ))}
                      </div>
                      <div className="flex-shrink-0 text-right">
                        <p className="font-display text-3xl font-bold" style={{ color: '#1B4332' }}>&pound;7</p>
                        <p className="text-xs" style={{ color: '#9CA3AF' }}>one-time</p>
                      </div>
                    </div>

                    {/* Document preview with blur */}
                    <div className="border overflow-hidden relative mb-4" style={{ borderColor: '#E5E5E2', backgroundColor: '#FFFFFF' }}>
                      {/* Visible preview */}
                      <div className="px-6 pt-6 pb-2">
                        <pre className="text-xs leading-relaxed font-mono whitespace-pre-wrap" style={{ color: '#1A1A1A' }}>
                          {contractContent.slice(0, 500)}
                        </pre>
                      </div>

                      {/* Blurred section */}
                      <div className="relative">
                        <div className="px-6 pt-2 pb-6" style={{ filter: 'blur(4px)', userSelect: 'none', pointerEvents: 'none' }}>
                          <pre className="text-xs leading-relaxed font-mono whitespace-pre-wrap" style={{ color: '#1A1A1A' }}>
                            {contractContent.slice(500, 1300)}
                          </pre>
                        </div>

                        {/* Paywall overlay */}
                        <div
                          className="absolute inset-0 flex flex-col items-center justify-center text-center px-6"
                          style={{ background: 'linear-gradient(to bottom, transparent 0%, rgba(255,255,255,0.9) 30%, rgba(255,255,255,0.98) 60%)' }}
                        >
                          <div className="w-10 h-10 flex items-center justify-center mb-3" style={{ backgroundColor: '#D8F3DC' }}>
                            <Eye className="w-5 h-5" style={{ color: '#2D6A4F' }} />
                          </div>
                          <h3 className="font-display text-base font-bold mb-1" style={{ color: '#1B4332' }}>Your contract is ready</h3>
                          <p className="text-sm mb-5 max-w-xs" style={{ color: '#6B7280' }}>
                            Unlock the full contract &mdash; download as PDF and Word, ready to sign and send.
                          </p>
                          <button
                            onClick={handleCheckout}
                            disabled={checkoutLoading}
                            className="inline-flex items-center gap-2 px-6 py-3 text-sm font-semibold text-white transition-opacity hover:opacity-90 disabled:opacity-60 mb-2"
                            style={{ backgroundColor: '#2D6A4F' }}
                          >
                            {checkoutLoading ? (
                              <><Loader2 className="w-4 h-4 animate-spin" /> Redirecting to payment&hellip;</>
                            ) : (
                              <><Download className="w-4 h-4" /> &pound;7 &mdash; Unlock full contract (PDF + Word)</>
                            )}
                          </button>
                          <p className="text-xs" style={{ color: '#9CA3AF' }}>Secure payment via Stripe &middot; Instant download</p>
                        </div>
                      </div>
                    </div>

                    <div className="text-center">
                      <a href={`/preview/${contractId}`} className="inline-flex items-center gap-1.5 text-sm font-medium hover:opacity-70 transition-opacity" style={{ color: '#2D6A4F' }}>
                        View full preview page <ExternalLink className="w-3.5 h-3.5" />
                      </a>
                    </div>
                  </div>
                )}
              </motion.div>
            )}

            {/* ── MY CONTRACTS ── */}
            {activeTab === 'my-contracts' && (
              <motion.div key="my-contracts" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <h1 className="font-display text-2xl font-bold" style={{ color: '#1B4332' }}>My Contracts</h1>
                    <p className="text-sm mt-0.5" style={{ color: '#6B7280' }}>{savedContracts.length} contract{savedContracts.length !== 1 ? 's' : ''} generated</p>
                  </div>
                  <button onClick={() => navigate('new-contract')} className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white transition-opacity hover:opacity-90" style={{ backgroundColor: '#2D6A4F' }}>
                    <Plus className="w-4 h-4" /> New Contract
                  </button>
                </div>

                {filtered.length === 0 ? (
                  <div className="flex flex-col items-center justify-center py-24 text-center border" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                    <div className="w-14 h-14 flex items-center justify-center mb-4" style={{ backgroundColor: '#D8F3DC' }}>
                      <FileText className="w-7 h-7" style={{ color: '#2D6A4F' }} />
                    </div>
                    <h2 className="font-display text-lg font-bold mb-2" style={{ color: '#1B4332' }}>
                      {searchQuery ? 'No contracts match your search' : 'No contracts yet'}
                    </h2>
                    <p className="text-sm mb-5 max-w-xs" style={{ color: '#6B7280' }}>
                      {searchQuery ? 'Try a different search term.' : 'Contracts you generate will appear here.'}
                    </p>
                    {!searchQuery && (
                      <button onClick={() => navigate('new-contract')} className="flex items-center gap-2 px-5 py-2.5 text-sm font-semibold text-white transition-opacity hover:opacity-90" style={{ backgroundColor: '#2D6A4F' }}>
                        <Plus className="w-4 h-4" /> Create your first contract
                      </button>
                    )}
                  </div>
                ) : (
                  <div className="border" style={{ borderColor: '#E5E5E2' }}>
                    {/* Header row */}
                    <div className="flex items-center gap-4 px-4 py-2.5 border-b text-xs font-bold uppercase tracking-widest" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8', color: '#9CA3AF' }}>
                      <div className="flex-1">Contract</div>
                      <div className="w-28 text-center hidden sm:block">Status</div>
                      <div className="w-32 text-right hidden md:block">Created</div>
                      <div className="w-24 text-right">Action</div>
                    </div>
                    {filtered.map((c, i) => (
                      <div key={c.id} className={cn('flex items-center gap-4 px-4 py-3.5 hover:bg-[#FAFAF8] transition-colors', i !== 0 && 'border-t')} style={{ borderColor: '#E5E5E2' }}>
                        <FileText className="w-4 h-4 flex-shrink-0" style={{ color: '#9CA3AF' }} />
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium truncate mb-0.5" style={{ color: '#1B4332' }}>{c.title}</p>
                          <p className="text-xs truncate" style={{ color: '#9CA3AF' }}>{c.typeName}{c.party1 ? ` &middot; ${c.party1}` : ''}</p>
                        </div>
                        <div className="w-28 text-center hidden sm:block">
                          <span className="text-xs font-bold px-2 py-0.5 uppercase tracking-wide"
                            style={c.status === 'paid' ? { backgroundColor: '#D8F3DC', color: '#1B4332' } : { backgroundColor: '#FEF3C7', color: '#92400E' }}
                          >
                            {c.status === 'paid' ? 'Downloaded' : 'Generated'}
                          </span>
                        </div>
                        <div className="w-32 text-right text-xs flex-shrink-0 hidden md:block" style={{ color: '#9CA3AF' }}>{fmtDate(c.createdAt)}</div>
                        <div className="w-24 text-right flex-shrink-0">
                          {c.status === 'generated' ? (
                            <button
                              onClick={() => initiateCheckout(c.id)}
                              className="text-xs font-semibold flex items-center gap-1 ml-auto hover:opacity-70 transition-opacity"
                              style={{ color: '#2D6A4F' }}
                            >
                              <Download className="w-3 h-3" /> Unlock
                            </button>
                          ) : (
                            <a href={`/download/${c.id}`} className="text-xs font-semibold flex items-center gap-1 ml-auto hover:opacity-70 transition-opacity" style={{ color: '#2D6A4F' }}>
                              <Download className="w-3 h-3" /> Download
                            </a>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </motion.div>
            )}

            {/* ── TEMPLATES ── */}
            {activeTab === 'templates' && (
              <motion.div key="templates" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
                <div className="mb-6">
                  <h1 className="font-display text-2xl font-bold mb-1" style={{ color: '#1B4332' }}>Contract templates</h1>
                  <p className="text-sm" style={{ color: '#6B7280' }}>8 UK-compliant contract templates. Click any to generate instantly.</p>
                </div>

                <div className="border" style={{ borderColor: '#E5E5E2' }}>
                  <div className="flex items-center gap-4 px-4 py-2.5 border-b text-xs font-bold uppercase tracking-widest" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8', color: '#9CA3AF' }}>
                    <div className="flex-1">Template</div>
                    <div className="w-56 hidden lg:block">Description</div>
                    <div className="w-24 text-right">Action</div>
                  </div>
                  {CONTRACT_TYPES.map((type, i) => {
                    const Icon = type.Icon
                    return (
                      <div key={type.id} className={cn('flex items-center gap-4 px-4 py-4 hover:bg-[#FAFAF8] transition-colors', i !== 0 && 'border-t')} style={{ borderColor: '#E5E5E2' }}>
                        <div className="w-9 h-9 flex items-center justify-center flex-shrink-0" style={{ backgroundColor: '#D8F3DC' }}>
                          <Icon className="w-4 h-4" style={{ color: '#2D6A4F' }} />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold" style={{ color: '#1B4332' }}>{type.title}</p>
                        </div>
                        <div className="w-56 hidden lg:block">
                          <p className="text-xs truncate" style={{ color: '#6B7280' }}>{type.description}</p>
                        </div>
                        <div className="w-24 text-right">
                          <button onClick={() => handleSelectType(type)} className="text-xs font-semibold flex items-center gap-1 ml-auto hover:opacity-70 transition-opacity" style={{ color: '#2D6A4F' }}>
                            Generate <ArrowRight className="w-3 h-3" />
                          </button>
                        </div>
                      </div>
                    )
                  })}
                </div>

                <div className="mt-6 border p-4 flex items-center gap-4" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                  <Zap className="w-5 h-5 flex-shrink-0" style={{ color: '#2D6A4F' }} />
                  <div className="flex-1">
                    <p className="text-sm font-semibold" style={{ color: '#1B4332' }}>All templates included in both plans</p>
                    <p className="text-xs" style={{ color: '#6B7280' }}>Pay &pound;7 per contract, or &pound;19/month for unlimited access to every template.</p>
                  </div>
                  <button onClick={() => navigate('pricing')} className="flex-shrink-0 text-xs font-semibold hover:opacity-70 transition-opacity" style={{ color: '#2D6A4F' }}>
                    See pricing &rarr;
                  </button>
                </div>
              </motion.div>
            )}

            {/* ── PRICING ── */}
            {activeTab === 'pricing' && (
              <motion.div key="pricing" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
                <div className="mb-6">
                  <h1 className="font-display text-2xl font-bold mb-1" style={{ color: '#1B4332' }}>Pricing</h1>
                  <p className="text-sm" style={{ color: '#6B7280' }}>Generate for free. Pay only when you download.</p>
                </div>

                <div className="grid sm:grid-cols-2 gap-5 max-w-2xl mb-6">
                  {/* Pay per doc */}
                  <div className="border-2 p-7" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                    <p className="text-xs font-bold uppercase tracking-widest mb-4" style={{ color: '#9CA3AF' }}>Pay as you go</p>
                    <div className="flex items-baseline gap-1 mb-1">
                      <span className="font-display text-5xl font-bold" style={{ color: '#1B4332' }}>&pound;7</span>
                      <span className="text-sm" style={{ color: '#6B7280' }}>/ contract</span>
                    </div>
                    <p className="text-sm mb-6" style={{ color: '#6B7280' }}>Generate and download one contract at a time.</p>
                    <ul className="space-y-2.5 mb-7">
                      {['Full UK-compliant contract', 'PDF + Word download', 'Tailored to your answers', 'No subscription needed'].map((f) => (
                        <li key={f} className="flex items-center gap-2.5 text-sm">
                          <Check className="w-4 h-4 flex-shrink-0" style={{ color: '#52B788' }} strokeWidth={3} />
                          <span style={{ color: '#1A1A1A' }}>{f}</span>
                        </li>
                      ))}
                    </ul>
                    <button onClick={() => navigate('new-contract')} className="w-full py-2.5 text-sm font-semibold border-2 transition-colors hover:bg-[#D8F3DC]" style={{ borderColor: '#2D6A4F', color: '#2D6A4F', backgroundColor: 'transparent' }}>
                      Generate a contract
                    </button>
                  </div>

                  {/* Unlimited */}
                  <div className="border-2 p-7 relative text-white" style={{ borderColor: '#2D6A4F', backgroundColor: '#2D6A4F' }}>
                    <div className="absolute -top-3.5 left-5 px-3 py-0.5 text-xs font-bold" style={{ backgroundColor: '#52B788', color: '#1B4332' }}>Best value</div>
                    <p className="text-xs font-bold uppercase tracking-widest mb-4" style={{ color: '#D8F3DC' }}>Unlimited</p>
                    <div className="flex items-baseline gap-1 mb-1">
                      <span className="font-display text-5xl font-bold">&pound;19</span>
                      <span className="text-sm" style={{ color: '#D8F3DC' }}>/month</span>
                    </div>
                    <p className="text-sm mb-6" style={{ color: '#D8F3DC' }}>Unlimited contracts for busy freelancers and teams.</p>
                    <ul className="space-y-2.5 mb-7">
                      {['All 8 contract types', 'Unlimited downloads', 'PDF + Word', 'Cancel any time'].map((f) => (
                        <li key={f} className="flex items-center gap-2.5 text-sm">
                          <Check className="w-4 h-4 flex-shrink-0" style={{ color: '#52B788' }} strokeWidth={3} />
                          <span>{f}</span>
                        </li>
                      ))}
                    </ul>
                    <button className="w-full py-2.5 text-sm font-semibold transition-opacity hover:opacity-90" style={{ backgroundColor: '#FFFFFF', color: '#1B4332' }}>
                      Get unlimited access
                    </button>
                  </div>
                </div>

                <div className="max-w-2xl border p-4 flex items-start gap-3" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                  <Star className="w-4 h-4 flex-shrink-0 mt-0.5 fill-current" style={{ color: '#F59E0B' }} />
                  <p className="text-sm" style={{ color: '#6B7280' }}>
                    A solicitor charges &pound;150&ndash;&pound;500 for the same document. One ClauseKit contract pays for 3 months of the unlimited plan. &middot; Secure payments via Stripe.
                  </p>
                </div>
              </motion.div>
            )}

            {/* ── HELP ── */}
            {activeTab === 'help' && (
              <motion.div key="help" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.18 }} className="p-6 lg:p-8">
                <div className="mb-6">
                  <h1 className="font-display text-2xl font-bold mb-1" style={{ color: '#1B4332' }}>Help &amp; FAQ</h1>
                  <p className="text-sm" style={{ color: '#6B7280' }}>Frequently asked questions about ClauseKit.</p>
                </div>

                {/* Trust strip */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8">
                  {[
                    { Icon: Shield, label: 'Solicitor-Reviewed' },
                    { Icon: Zap, label: 'GPT-4o Powered' },
                    { Icon: FileText, label: 'UK Law Only' },
                    { Icon: Lock, label: 'GDPR Compliant' },
                  ].map((t) => (
                    <div key={t.label} className="flex items-center gap-2.5 border p-3" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                      <t.Icon className="w-4 h-4 flex-shrink-0" style={{ color: '#2D6A4F' }} />
                      <span className="text-xs font-semibold" style={{ color: '#1B4332' }}>{t.label}</span>
                    </div>
                  ))}
                </div>

                <div className="max-w-2xl border" style={{ borderColor: '#E5E5E2', backgroundColor: '#FFFFFF' }}>
                  <div className="px-6 divide-y" style={{ borderColor: '#E5E5E2' }}>
                    {FAQS.map((item) => <FaqItem key={item.q} q={item.q} a={item.a} />)}
                  </div>
                </div>

                <div className="max-w-2xl mt-5 border p-5 flex items-center gap-4" style={{ borderColor: '#E5E5E2', backgroundColor: '#FAFAF8' }}>
                  <div className="w-10 h-10 flex items-center justify-center flex-shrink-0" style={{ backgroundColor: '#25D366' }}>
                    <svg className="w-5 h-5 text-white" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
                    </svg>
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-semibold mb-0.5" style={{ color: '#1B4332' }}>Still have a question?</p>
                    <p className="text-xs" style={{ color: '#6B7280' }}>Message us on WhatsApp. We usually reply within an hour.</p>
                  </div>
                  <a href="https://wa.me/447700900000" target="_blank" rel="noreferrer" className="flex-shrink-0 px-4 py-2 text-xs font-semibold text-white transition-opacity hover:opacity-90" style={{ backgroundColor: '#25D366' }}>
                    Chat with us
                  </a>
                </div>
              </motion.div>
            )}

          </AnimatePresence>
        </main>
      </div>
    </div>
  )
}
