import Link from 'next/link'
import { FileText } from 'lucide-react'

export const metadata = { title: 'Terms & Conditions — ClauseKit' }

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: '#FAFAF8', fontFamily: 'Inter, sans-serif' }}>
      <div className="flex items-center justify-center gap-3 px-4 py-2 text-xs font-medium w-full" style={{ backgroundColor: '#1B4332', color: '#D8F3DC' }}>
        <span>UK law only</span><span style={{ color: '#52B788' }}>·</span>
        <span>Solicitor-reviewed</span><span style={{ color: '#52B788' }}>·</span>
        <span>ClauseKit</span>
      </div>
      <header className="border-b bg-white" style={{ borderColor: '#E5E5E2' }}>
        <div className="max-w-3xl mx-auto px-6 h-12 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-6 h-6 flex items-center justify-center" style={{ backgroundColor: '#2D6A4F' }}>
              <FileText className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="font-bold text-sm tracking-tight" style={{ color: '#1B4332' }}>ClauseKit</span>
          </Link>
          <Link href="/app" className="text-xs font-medium hover:opacity-70" style={{ color: '#2D6A4F' }}>← Back to dashboard</Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <div className="border bg-white p-8" style={{ borderColor: '#E5E5E2' }}>
          <p className="text-[10px] font-bold uppercase tracking-widest mb-2" style={{ color: '#9CA3AF' }}>Last updated: 29 March 2026</p>
          <h1 className="text-2xl font-bold mb-6" style={{ color: '#1B4332' }}>Terms & Conditions</h1>

          <div className="space-y-6 text-sm leading-relaxed" style={{ color: '#374151' }}>
            <section>
              <h2 className="text-base font-bold mb-2" style={{ color: '#1B4332' }}>1. About ClauseKit</h2>
              <p>ClauseKit is operated by JWebDesign and provides AI-assisted UK contract generation. By using our service you agree to these terms. These terms are governed by the laws of England and Wales.</p>
            </section>

            <section>
              <h2 className="text-base font-bold mb-2" style={{ color: '#1B4332' }}>2. Not legal advice</h2>
              <p>ClauseKit generates contract documents based on your inputs. <strong>This is not legal advice.</strong> The documents produced are intended as a starting point and may not be suitable for every situation. For high-value, complex, or novel matters we recommend review by a qualified UK solicitor. We accept no liability for any loss arising from reliance on documents generated by ClauseKit.</p>

            </section>

            <section>
              <h2 className="text-base font-bold mb-2" style={{ color: '#1B4332' }}>3. Pricing and payment</h2>
              <ul className="space-y-2 ml-4">
                <li><strong>Pay-per-doc:</strong> £7 per contract download, charged at the time of download via Stripe</li>
                <li><strong>Pro plan:</strong> £19/month, billed monthly, up to 20 contract generations per day</li>
                <li>All prices include VAT where applicable</li>
                <li>Payments are processed by Stripe. We do not store card details.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-base font-bold mb-2" style={{ color: '#1B4332' }}>4. Refunds</h2>
              <p>Please see our <Link href="/refunds" className="underline" style={{ color: '#2D6A4F' }}>Refund Policy</Link> for full details. In summary: pay-per-doc purchases are non-refundable once the document has been downloaded. Pro plan subscriptions may be cancelled at any time with no further charges.</p>
            </section>

            <section>
              <h2 className="text-base font-bold mb-2" style={{ color: '#1B4332' }}>5. Acceptable use</h2>
              <p>You may not use ClauseKit to:</p>
              <ul className="space-y-2 ml-4 mt-2">
                <li>Generate documents for illegal purposes</li>
                <li>Automate or scrape contract generation via bots or scripts</li>
                <li>Resell or redistribute generated documents as your own product</li>
                <li>Attempt to reverse-engineer or circumvent our rate limits or paywalls</li>
              </ul>
            </section>

            <section>
              <h2 className="text-base font-bold mb-2" style={{ color: '#1B4332' }}>6. Intellectual property</h2>
              <p>You own the contracts you generate using ClauseKit. The ClauseKit platform, brand, and underlying software remain our intellectual property.</p>
            </section>

            <section>
              <h2 className="text-base font-bold mb-2" style={{ color: '#1B4332' }}>7. Limitation of liability</h2>
              <p>To the maximum extent permitted by law, ClauseKit&apos;s total liability to you shall not exceed the amount you paid in the 12 months preceding the claim. We exclude all liability for indirect, consequential, or special losses including lost profits, lost contracts, or lost data.</p>
            </section>

            <section>
              <h2 className="text-base font-bold mb-2" style={{ color: '#1B4332' }}>8. Governing law</h2>
              <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
            </section>
          </div>
        </div>
      </main>
    </div>
  )
}
