import { NextRequest, NextResponse } from 'next/server'
import { getContractAsync } from '@/lib/contract-store'
import { stripe } from '@/lib/stripe'
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  BorderStyle, ShadingType,
} from 'docx'

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const contractId = searchParams.get('contractId')
  const sessionId = searchParams.get('session')

  if (!contractId || !sessionId) {
    return NextResponse.json({ error: 'Missing contractId or session' }, { status: 400 })
  }

  // Verify payment
  try {
    const session = await stripe.checkout.sessions.retrieve(sessionId)
    if (session.payment_status !== 'paid') {
      return NextResponse.json({ error: 'Payment not confirmed' }, { status: 402 })
    }
    if (session.metadata?.contractId !== contractId) {
      return NextResponse.json({ error: 'Session does not match contract' }, { status: 403 })
    }
  } catch {
    return NextResponse.json({ error: 'Invalid session' }, { status: 400 })
  }

  const record = await getContractAsync(contractId)
  if (!record) return NextResponse.json({ error: 'Contract not found' }, { status: 404 })

  // Build Word document
  const lines = record.content.split('\n')
  const children: Paragraph[] = []

  // Header
  children.push(
    new Paragraph({
      text: 'ClauseKit',
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      shading: { type: ShadingType.SOLID, color: '2D6A4F' },
    }),
    new Paragraph({
      text: record.title,
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      text: `Generated: ${new Date(record.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  )

  // Party block
  if (record.party1 || record.party2) {
    children.push(new Paragraph({
      text: 'PARTIES',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 300, after: 120 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: '2D6A4F' } },
    }))
    if (record.party1) {
      children.push(
        new Paragraph({ text: `Party 1: ${record.party1.name}`, spacing: { after: 60 } }),
        new Paragraph({ text: `Email: ${record.party1.email}`, spacing: { after: 60 } }),
        new Paragraph({ text: `Address: ${record.party1.address}`, spacing: { after: 200 } }),
      )
    }
    if (record.party2) {
      children.push(
        new Paragraph({ text: `Party 2: ${record.party2.name}`, spacing: { after: 60 } }),
        new Paragraph({ text: `Email: ${record.party2.email}`, spacing: { after: 60 } }),
        new Paragraph({ text: `Address: ${record.party2.address}`, spacing: { after: 300 } }),
      )
    }
  }

  // Contract content
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) { children.push(new Paragraph({ text: '', spacing: { after: 120 } })); continue }

    const isH1 = /^\d{2}\.\s+[A-Z]/.test(trimmed)
    const isH2 = trimmed === trimmed.toUpperCase() && trimmed.length < 80 && trimmed.length > 2
    const isSignature = trimmed.startsWith('PARTY 1 —') || trimmed.startsWith('PARTY 2 —') || trimmed.includes('Signature:')

    if (isH1) {
      children.push(new Paragraph({
        text: trimmed,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 120 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: 'CCCCCC' } },
      }))
    } else if (isH2) {
      children.push(new Paragraph({
        text: trimmed,
        heading: HeadingLevel.HEADING_3,
        spacing: { before: 200, after: 80 },
      }))
    } else if (isSignature) {
      children.push(new Paragraph({
        children: [new TextRun({ text: trimmed, bold: true })],
        spacing: { after: 120 },
      }))
    } else if (trimmed.startsWith('---')) {
      children.push(new Paragraph({
        text: '',
        border: { top: { style: BorderStyle.SINGLE, size: 6, color: 'AAAAAA' } },
        spacing: { before: 200, after: 200 },
      }))
    } else {
      children.push(new Paragraph({
        text: trimmed,
        spacing: { after: 100 },
      }))
    }
  }

  // Footer
  children.push(
    new Paragraph({ text: '', spacing: { before: 400 } }),
    new Paragraph({
      text: 'This document was generated by ClauseKit. It is not legal advice.',
      alignment: AlignmentType.CENTER,
      border: { top: { style: BorderStyle.SINGLE, size: 4, color: 'CCCCCC' } },
      spacing: { before: 200 },
    }),
  )

  const doc = new Document({
    sections: [{
      properties: {
        page: {
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      children,
    }],
    styles: {
      paragraphStyles: [
        {
          id: 'Heading1',
          name: 'Heading 1',
          basedOn: 'Normal',
          run: { size: 32, bold: true, color: '1B4332' },
        },
        {
          id: 'Heading2',
          name: 'Heading 2',
          basedOn: 'Normal',
          run: { size: 24, bold: true, color: '2D6A4F' },
        },
        {
          id: 'Heading3',
          name: 'Heading 3',
          basedOn: 'Normal',
          run: { size: 20, bold: true, color: '374151' },
        },
      ],
    },
  })

  const buffer = await Packer.toBuffer(doc)
  const filename = record.title.replace(/[^a-zA-Z0-9\-_ ]/g, '').replace(/\s+/g, '-').toLowerCase()

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${filename}.docx"`,
      'Cache-Control': 'no-store',
    },
  })
}
