import { NextRequest, NextResponse } from 'next/server';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { stripe } from '@/lib/stripe';
import { getContract } from '@/lib/contract-store';

const DISCLAIMER =
  'Generated by AI — not legal advice. Consider review by a qualified solicitor before signing.';

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const contractId = searchParams.get('contractId');
  const sessionId = searchParams.get('session');

  if (!contractId || !sessionId) {
    return NextResponse.json({ error: 'Missing contractId or session' }, { status: 400 });
  }

  // Verify payment
  try {
    const session = await stripe.checkout.sessions.retrieve(sessionId);
    if (session.payment_status !== 'paid') {
      return NextResponse.json({ error: 'Payment not confirmed' }, { status: 402 });
    }
    // Ensure session belongs to this contract
    if (session.metadata?.contractId !== contractId) {
      return NextResponse.json({ error: 'Session does not match contract' }, { status: 403 });
    }
  } catch {
    return NextResponse.json({ error: 'Invalid session' }, { status: 400 });
  }

  const record = getContract(contractId);
  if (!record) {
    return NextResponse.json({ error: 'Contract not found' }, { status: 404 });
  }

  // Generate PDF
  const pdfDoc = await PDFDocument.create();
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const PAGE_WIDTH = 595;
  const PAGE_HEIGHT = 842;
  const MARGIN = 56;
  const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
  const HEADER_HEIGHT = 72;
  const FOOTER_HEIGHT = 40;
  const LINE_HEIGHT = 16;
  const BODY_FONT_SIZE = 10;
  const TITLE_FONT_SIZE = 16;
  const SECTION_FONT_SIZE = 11;

  function addPage() {
    const page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

    // Header bar — ClauseKit green
    page.drawRectangle({
      x: 0,
      y: PAGE_HEIGHT - HEADER_HEIGHT,
      width: PAGE_WIDTH,
      height: HEADER_HEIGHT,
      color: rgb(0.176, 0.263, 0.31), // #2D6A4F
    });

    // Logo / brand in header
    page.drawText('ClauseKit', {
      x: MARGIN,
      y: PAGE_HEIGHT - HEADER_HEIGHT + 24,
      font: boldFont,
      size: 18,
      color: rgb(1, 1, 1),
    });

    page.drawText('clausekit.com', {
      x: PAGE_WIDTH - MARGIN - 70,
      y: PAGE_HEIGHT - HEADER_HEIGHT + 24,
      font: regularFont,
      size: 10,
      color: rgb(0.8, 0.85, 1),
    });

    // Footer
    page.drawRectangle({
      x: 0,
      y: 0,
      width: PAGE_WIDTH,
      height: FOOTER_HEIGHT,
      color: rgb(0.97, 0.97, 0.98),
    });

    page.drawText(DISCLAIMER, {
      x: MARGIN,
      y: 14,
      font: regularFont,
      size: 8,
      color: rgb(0.55, 0.55, 0.6),
      maxWidth: CONTENT_WIDTH - 60,
    });

    return page;
  }

  // Split content into lines that fit within content width
  function wrapText(text: string, font: typeof regularFont, fontSize: number, maxWidth: number): string[] {
    const words = text.split(' ');
    const lines: string[] = [];
    let current = '';

    for (const word of words) {
      const test = current ? `${current} ${word}` : word;
      const w = font.widthOfTextAtSize(test, fontSize);
      if (w > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
    return lines;
  }

  const rawLines = record.content.split('\n');

  let page = addPage();
  let y = PAGE_HEIGHT - HEADER_HEIGHT - 32;
  let pageNum = 1;

  // Title
  const titleLines = wrapText(record.title, boldFont, TITLE_FONT_SIZE, CONTENT_WIDTH);
  for (const line of titleLines) {
    if (y < FOOTER_HEIGHT + LINE_HEIGHT * 2) {
      page = addPage();
      pageNum++;
      y = PAGE_HEIGHT - HEADER_HEIGHT - 32;
    }
    page.drawText(line, {
      x: MARGIN,
      y,
      font: boldFont,
      size: TITLE_FONT_SIZE,
      color: rgb(0.1, 0.1, 0.15),
    });
    y -= TITLE_FONT_SIZE + 4;
  }

  y -= 12;

  // Body content
  for (const rawLine of rawLines) {
    const trimmed = rawLine.trim();

    // Detect section headings: lines that are ALL CAPS or start with a number + dot
    const isHeading =
      (trimmed.length > 0 && trimmed === trimmed.toUpperCase() && trimmed.length < 80) ||
      /^\d+\.\s+[A-Z]/.test(trimmed);

    const font = isHeading ? boldFont : regularFont;
    const fontSize = isHeading ? SECTION_FONT_SIZE : BODY_FONT_SIZE;
    const topPad = isHeading ? 8 : 0;

    if (trimmed === '') {
      y -= LINE_HEIGHT * 0.6;
      continue;
    }

    const wrappedLines = wrapText(trimmed, font, fontSize, CONTENT_WIDTH);

    for (const wl of wrappedLines) {
      if (y < FOOTER_HEIGHT + LINE_HEIGHT * 2) {
        // Add page number to current page footer before flipping
        page.drawText(`Page ${pageNum}`, {
          x: PAGE_WIDTH - MARGIN - 30,
          y: 14,
          font: regularFont,
          size: 8,
          color: rgb(0.55, 0.55, 0.6),
        });

        page = addPage();
        pageNum++;
        y = PAGE_HEIGHT - HEADER_HEIGHT - 32;
      }

      y -= topPad;
      page.drawText(wl, {
        x: MARGIN,
        y,
        font,
        size: fontSize,
        color: isHeading ? rgb(0.1, 0.1, 0.15) : rgb(0.2, 0.2, 0.25),
      });
      y -= fontSize + 4;
    }
  }

  // Page number on last page
  page.drawText(`Page ${pageNum}`, {
    x: PAGE_WIDTH - MARGIN - 30,
    y: 14,
    font: regularFont,
    size: 8,
    color: rgb(0.55, 0.55, 0.6),
  });

  const pdfBytes = await pdfDoc.save();

  const filename = record.title.replace(/[^a-zA-Z0-9\-_ ]/g, '').replace(/\s+/g, '-').toLowerCase();

  return new NextResponse(Buffer.from(pdfBytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}.pdf"`,
      'Cache-Control': 'no-store',
    },
  });
}
